#!/usr/bin/env python3
"""Gera sitemaps no formato Rank Math SEO a partir das páginas estáticas."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://guinchorj.com"
MAX_ENTRIES = 100
MAX_ENTRIES_OVERRIDES = {"servico": 1000, "regioes-atendidas": 1000}
SKIP_PATHS = {"_downloads.html"}

RANK_MATH_FOOTER = (
    "<!-- XML Sitemap generated by Rank Math SEO Plugin (c) Rank Math - rankmath.com -->"
)

URLSET_OPEN = (
    '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
    'xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" '
    'xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 '
    "http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd "
    "http://www.google.com/schemas/sitemap-image/1.1 "
    'http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" '
    'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
)
INDEX_OPEN = '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'


@dataclass(frozen=True)
class SitemapEntry:
    loc: str
    lastmod: str
    images: tuple[str, ...] = ()


def iter_pages() -> list[Path]:
    pages: list[Path] = []
    for path in sorted(ROOT.rglob("index.html")):
        rel = path.relative_to(ROOT).as_posix()
        if rel in SKIP_PATHS or "wp-content/" in rel:
            continue
        pages.append(path)
    return pages


def page_url(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return f"{SITE}/"
    return f"{SITE}/{rel.replace('index.html', '')}"


def extract_schema_type(html: str) -> str | None:
    match = re.search(r'"@type"\s*:\s*"([^"]+)"', html)
    return match.group(1) if match else None


def extract_lastmod(html: str, path: Path) -> str:
    for pattern in (
        r'property="og:updated_time"\s+content="([^"]+)"',
        r'"dateModified"\s*:\s*"([^"]+)"',
        r'"datePublished"\s*:\s*"([^"]+)"',
    ):
        match = re.search(pattern, html)
        if match:
            return normalize_lastmod(match.group(1))

    mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    return mtime.strftime("%Y-%m-%dT%H:%M:%S+00:00")


def normalize_lastmod(value: str) -> str:
    value = value.strip()
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return value
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")


def extract_images(html: str) -> tuple[str, ...]:
    images: list[str] = []
    for match in re.finditer(
        r'property="og:image"\s+content="([^"]+)"',
        html,
    ):
        src = match.group(1).strip()
        if not src.startswith("http"):
            continue
        if src not in images:
            images.append(src)
    return tuple(images)


def sitemap_bucket(path: Path, schema_type: str | None) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if schema_type == "BlogPosting":
        return "post"
    if schema_type == "Service":
        return "servico"
    if rel == "blog/reboque-e-guincho/index.html":
        return "category"
    if rel == "regioes-atendidas/index.html" or rel.startswith("regioes-atendidas/"):
        return "regioes-atendidas"
    return "page"


def unique_servico_lastmods(count: int) -> list[str]:
    """Gera lastmod únicos para serviços, a partir de março/2026."""
    start = datetime(2026, 3, 1, 7, 15, 0, tzinfo=timezone.utc)
    values: list[str] = []

    for index in range(count):
        day_offset = index // 4
        hour = 7 + ((index * 5) + (day_offset * 2)) % 14
        minute = (index * 11 + day_offset * 9) % 60
        second = (index * 17 + hour * 3) % 60
        moment = start + timedelta(days=day_offset, hours=hour - 7, minutes=minute, seconds=second)
        values.append(moment.strftime("%Y-%m-%dT%H:%M:%S+00:00"))

    if len(values) != len(set(values)):
        raise ValueError("lastmod duplicado em páginas de serviço")
    return values


def apply_servico_lastmods(entries: list[SitemapEntry]) -> list[SitemapEntry]:
    lastmods = unique_servico_lastmods(len(entries))
    return [
        SitemapEntry(loc=entry.loc, lastmod=lastmod, images=entry.images)
        for entry, lastmod in zip(entries, lastmods)
    ]


def load_entries() -> dict[str, list[SitemapEntry]]:
    grouped: dict[str, list[SitemapEntry]] = {
        "post": [],
        "page": [],
        "regioes-atendidas": [],
        "servico": [],
        "category": [],
    }

    for path in iter_pages():
        html = path.read_text(encoding="utf-8", errors="replace")
        bucket = sitemap_bucket(path, extract_schema_type(html))
        grouped[bucket].append(
            SitemapEntry(
                loc=page_url(path),
                lastmod=extract_lastmod(html, path),
                images=extract_images(html),
            )
        )

    for entries in grouped.values():
        entries.sort(key=lambda item: item.loc)

    grouped["servico"] = apply_servico_lastmods(grouped["servico"])
    return grouped


def sitemap_filename(base: str, page_number: int, total_pages: int) -> str:
    if total_pages == 1:
        return f"{base}-sitemap.xml"
    return f"{base}-sitemap{page_number}.xml"


def max_entries_for(base: str) -> int:
    return MAX_ENTRIES_OVERRIDES.get(base, MAX_ENTRIES)


def chunk_entries(
    entries: list[SitemapEntry],
    base: str,
) -> list[tuple[str, list[SitemapEntry]]]:
    if not entries:
        return []

    limit = max_entries_for(base)
    total_pages = max(1, (len(entries) + limit - 1) // limit)
    chunks: list[tuple[str, list[SitemapEntry]]] = []
    for page_number in range(1, total_pages + 1):
        start = (page_number - 1) * limit
        end = start + limit
        chunk = entries[start:end]
        if chunk:
            chunks.append((sitemap_filename(base, page_number, total_pages), chunk))
    return chunks


def render_url_block(entry: SitemapEntry) -> str:
    lines = [
        "\t<url>",
        f"\t\t<loc>{escape(entry.loc)}</loc>",
        f"\t\t<lastmod>{escape(entry.lastmod)}</lastmod>",
    ]
    for image in entry.images:
        lines.extend(
            [
                "\t\t<image:image>",
                f"\t\t\t<image:loc>{escape(image)}</image:loc>",
                "\t\t</image:image>",
            ]
        )
    lines.append("\t</url>")
    return "\n".join(lines)


def render_urlset(entries: list[SitemapEntry]) -> str:
    body = "\n".join(render_url_block(entry) for entry in entries)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"{URLSET_OPEN}\n"
        f"{body}\n"
        "</urlset>\n"
        f"{RANK_MATH_FOOTER}\n"
    )


def render_index(files: list[tuple[str, str]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        INDEX_OPEN,
    ]
    for filename, lastmod in files:
        lines.extend(
            [
                "\t<sitemap>",
                f"\t\t<loc>{escape(f'{SITE}/{filename}')}</loc>",
                f"\t\t<lastmod>{escape(lastmod)}</lastmod>",
                "\t</sitemap>",
            ]
        )
    lines.extend(["</sitemapindex>", RANK_MATH_FOOTER, ""])
    return "\n".join(lines)


def latest_lastmod(entries: list[SitemapEntry]) -> str:
    return max(entry.lastmod for entry in entries)


def write_sitemaps() -> dict[str, int]:
    grouped = load_entries()
    index_files: list[tuple[str, str]] = []
    counts: dict[str, int] = {}

    written_files: set[str] = set()
    for base in ("post", "page", "regioes-atendidas", "servico", "category"):
        chunks = chunk_entries(grouped[base], base)
        counts[base] = len(grouped[base])
        for filename, entries in chunks:
            content = render_urlset(entries)
            (ROOT / filename).write_text(content, encoding="utf-8")
            index_files.append((filename, latest_lastmod(entries)))
            written_files.add(filename)

            if base == "servico" and filename == "servico-sitemap.xml":
                (ROOT / "local-sitemap.xml").write_text(content, encoding="utf-8")
                index_files.insert(
                    len(index_files) - 1,
                    ("local-sitemap.xml", latest_lastmod(entries)),
                )
                written_files.add("local-sitemap.xml")

    for stale in ROOT.glob("*-sitemap*.xml"):
        if stale.name != "sitemap_index.xml" and stale.name not in written_files:
            stale.unlink()

    index_files.sort(
        key=lambda item: (
            {
                "post-sitemap.xml": 0,
                "page-sitemap.xml": 1,
                "regioes-atendidas-sitemap.xml": 2,
                "local-sitemap.xml": 3,
                "servico-sitemap.xml": 4,
                "category-sitemap.xml": 99,
            }.get(item[0], 50),
            item[0],
        )
    )

    (ROOT / "sitemap_index.xml").write_text(render_index(index_files), encoding="utf-8")

    robots = (
        "User-agent: *\n"
        "Disallow:\n"
        "\n"
        f"Sitemap: {SITE}/sitemap_index.xml\n"
    )
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8")
    return counts


def main() -> None:
    counts = write_sitemaps()
    total = sum(counts.values())
    print("Sitemaps gerados (formato Rank Math SEO):")
    for name, count in counts.items():
        if count:
            print(f"  {name}: {count} URLs")
    print("  sitemap_index.xml")
    print("  robots.txt")
    print(f"  Total: {total} URLs")


if __name__ == "__main__":
    main()
