#!/usr/bin/env python3
"""Gera sitemaps no formato Rank Math SEO a partir das páginas estáticas."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://guinchorj.com"
MAX_ENTRIES = 100
MAX_ENTRIES_OVERRIDES = {"servico": 1000, "regioes-atendidas": 1000}
SKIP_PATHS = {"_downloads.html"}

RANK_MATH_FOOTER = (
    "<!-- XML Sitemap generated by Rank Math SEO Plugin (c) Rank Math - rankmath.com -->"
)

URLSET_OPEN = (
    '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
    'xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" '
    'xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 '
    "http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd "
    "http://www.google.com/schemas/sitemap-image/1.1 "
    'http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" '
    'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
)
INDEX_OPEN = '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'


@dataclass(frozen=True)
class LocalBusiness:
    name: str
    description: str
    url: str
    phone: str
    email: str
    address: str
    latitude: str
    longitude: str
    lastmod: str


@dataclass(frozen=True)
class SitemapEntry:
    loc: str
    lastmod: str
    images: tuple[str, ...] = ()


def iter_pages() -> list[Path]:
    pages: list[Path] = []
    for path in sorted(ROOT.rglob("index.html")):
        rel = path.relative_to(ROOT).as_posix()
        if rel in SKIP_PATHS or "wp-content/" in rel:
            continue
        pages.append(path)
    return pages


def page_url(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return f"{SITE}/"
    return f"{SITE}/{rel.replace('index.html', '')}"


def extract_schema_type(html: str) -> str | None:
    match = re.search(r'"@type"\s*:\s*"([^"]+)"', html)
    return match.group(1) if match else None


def extract_lastmod(html: str, path: Path) -> str:
    for pattern in (
        r'property="og:updated_time"\s+content="([^"]+)"',
        r'"dateModified"\s*:\s*"([^"]+)"',
        r'"datePublished"\s*:\s*"([^"]+)"',
    ):
        match = re.search(pattern, html)
        if match:
            return normalize_lastmod(match.group(1))

    mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    return mtime.strftime("%Y-%m-%dT%H:%M:%S+00:00")


def normalize_lastmod(value: str) -> str:
    value = value.strip()
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return value
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")


def extract_images(html: str) -> tuple[str, ...]:
    images: list[str] = []
    for match in re.finditer(
        r'property="og:image"\s+content="([^"]+)"',
        html,
    ):
        src = match.group(1).strip()
        if not src.startswith("http"):
            continue
        if src not in images:
            images.append(src)
    return tuple(images)


def sitemap_bucket(path: Path, schema_type: str | None) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if schema_type == "BlogPosting":
        return "post"
    if schema_type == "Service":
        return "servico"
    if rel == "blog/reboque-e-guincho/index.html":
        return "category"
    if rel == "regioes-atendidas/index.html" or rel.startswith("regioes-atendidas/"):
        return "regioes-atendidas"
    return "page"


def unique_servico_lastmods(count: int) -> list[str]:
    """Gera lastmod únicos para serviços, a partir de março/2026."""
    start = datetime(2026, 3, 1, 7, 15, 0, tzinfo=timezone.utc)
    values: list[str] = []

    for index in range(count):
        day_offset = index // 4
        hour = 7 + ((index * 5) + (day_offset * 2)) % 14
        minute = (index * 11 + day_offset * 9) % 60
        second = (index * 17 + hour * 3) % 60
        moment = start + timedelta(days=day_offset, hours=hour - 7, minutes=minute, seconds=second)
        values.append(moment.strftime("%Y-%m-%dT%H:%M:%S+00:00"))

    if len(values) != len(set(values)):
        raise ValueError("lastmod duplicado em páginas de serviço")
    return values


def apply_servico_lastmods(entries: list[SitemapEntry]) -> list[SitemapEntry]:
    lastmods = unique_servico_lastmods(len(entries))
    return [
        SitemapEntry(loc=entry.loc, lastmod=lastmod, images=entry.images)
        for entry, lastmod in zip(entries, lastmods)
    ]


def load_entries() -> dict[str, list[SitemapEntry]]:
    grouped: dict[str, list[SitemapEntry]] = {
        "post": [],
        "page": [],
        "regioes-atendidas": [],
        "servico": [],
        "category": [],
    }

    for path in iter_pages():
        html = path.read_text(encoding="utf-8", errors="replace")
        bucket = sitemap_bucket(path, extract_schema_type(html))
        grouped[bucket].append(
            SitemapEntry(
                loc=page_url(path),
                lastmod=extract_lastmod(html, path),
                images=extract_images(html),
            )
        )

    for entries in grouped.values():
        entries.sort(key=lambda item: item.loc)

    grouped["servico"] = apply_servico_lastmods(grouped["servico"])
    return grouped


def sitemap_filename(base: str, page_number: int, total_pages: int) -> str:
    if total_pages == 1:
        return f"{base}-sitemap.xml"
    return f"{base}-sitemap{page_number}.xml"


def max_entries_for(base: str) -> int:
    return MAX_ENTRIES_OVERRIDES.get(base, MAX_ENTRIES)


def chunk_entries(
    entries: list[SitemapEntry],
    base: str,
) -> list[tuple[str, list[SitemapEntry]]]:
    if not entries:
        return []

    limit = max_entries_for(base)
    total_pages = max(1, (len(entries) + limit - 1) // limit)
    chunks: list[tuple[str, list[SitemapEntry]]] = []
    for page_number in range(1, total_pages + 1):
        start = (page_number - 1) * limit
        end = start + limit
        chunk = entries[start:end]
        if chunk:
            chunks.append((sitemap_filename(base, page_number, total_pages), chunk))
    return chunks


def extract_local_business() -> LocalBusiness:
    index_path = ROOT / "index.html"
    html = index_path.read_text(encoding="utf-8", errors="replace")
    business: dict | None = None

    for match in re.finditer(
        r'<script[^>]*type="application/ld\+json"[^>]*>(.*?)</script>',
        html,
        re.S,
    ):
        try:
            data = json.loads(match.group(1))
        except json.JSONDecodeError:
            continue

        items = data.get("@graph", [data]) if isinstance(data, dict) else data
        for item in items:
            item_type = item.get("@type", [])
            if isinstance(item_type, str):
                item_type = [item_type]
            if "LocalBusiness" in item_type:
                business = item
                break
        if business:
            break

    if not business:
        raise ValueError("LocalBusiness não encontrado em index.html")

    address = business.get("address", {})
    street = address.get("streetAddress", "").strip()
    locality = address.get("addressLocality", "Rio de Janeiro").strip()
    region = address.get("addressRegion", "RJ").strip()
    postal = address.get("postalCode", "20071-002").strip()
    country = address.get("addressCountry", "BR").strip()

    geo = business.get("geo", {})
    latitude = str(geo.get("latitude", "-22.90942221073698")).strip()
    longitude = str(geo.get("longitude", "-43.204173832005104")).strip()

    phone = business.get("telephone", "(21) 95954-3043").strip()
    phone_digits = re.sub(r"\D", "", phone)
    if phone_digits.startswith("55") and len(phone_digits) >= 12:
        formatted_phone = (
            f"+55-{phone_digits[2:4]}-{phone_digits[4:9]}-{phone_digits[9:]}"
        )
    elif len(phone_digits) == 11:
        formatted_phone = (
            f"+55-{phone_digits[:2]}-{phone_digits[2:7]}-{phone_digits[7:]}"
        )
    elif len(phone_digits) == 10:
        formatted_phone = (
            f"+55-{phone_digits[:2]}-{phone_digits[2:6]}-{phone_digits[6:]}"
        )
    else:
        formatted_phone = phone

    description = business.get("description", "").strip()
    meta = re.search(r'name="description"\s+content="([^"]+)"', html)
    if meta:
        description = meta.group(1).strip()

    cep_match = re.search(r"CEP\s*(\d{5}-?\d{3})", street, re.I)
    if cep_match:
        postal = cep_match.group(1)

    address_parts = [street, locality, region, postal, country]
    address_line = ", ".join(part for part in address_parts if part)

    return LocalBusiness(
        name=business.get("name", "Guincho RJ").strip(),
        description=description,
        url=SITE + "/",
        phone=formatted_phone,
        email=business.get("email", "contato@guinchorj.com").strip(),
        address=address_line,
        latitude=latitude,
        longitude=longitude,
        lastmod=extract_lastmod(html, index_path),
    )


def render_locations_kml(business: LocalBusiness) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">',
        "\t<Document>",
        f"\t\t<name>Locations for {escape(business.name)}</name>",
        "\t\t<open>1</open>",
        "\t\t<Folder>",
        f'\t\t\t<atom:link href="{escape(business.url)}" />',
        "\t\t\t<Placemark>",
        f"\t\t\t\t<name><![CDATA[{business.name}]]></name>",
        f"\t\t\t\t<description><![CDATA[{business.description}]]></description>",
        f"\t\t\t\t<address><![CDATA[{business.address}]]></address>",
        f"\t\t\t\t<phoneNumber><![CDATA[{business.phone}]]></phoneNumber>",
        f'\t\t\t\t<atom:link href="{escape(business.url)}"/>',
        "\t\t\t\t<LookAt>",
        f"\t\t\t\t\t<latitude>{escape(business.latitude)}</latitude>",
        f"\t\t\t\t\t<longitude>{escape(business.longitude)}</longitude>",
        "\t\t\t\t\t<altitude>0</altitude>",
        "\t\t\t\t\t<range></range>",
        "\t\t\t\t\t<tilt>0</tilt>",
        "\t\t\t\t</LookAt>",
        "\t\t\t\t<Point>",
        f"\t\t\t\t\t<coordinates>{escape(business.longitude)},{escape(business.latitude)}</coordinates>",
        "\t\t\t\t</Point>",
        "\t\t\t</Placemark>",
        "\t\t</Folder>",
        "\t</Document>",
        "</kml>",
        RANK_MATH_FOOTER,
        "",
    ]
    return "\n".join(lines)


def render_local_sitemap(business: LocalBusiness) -> str:
    kml_url = f"{SITE}/locations.kml"
    body = "\n".join(
        [
            "\t<url>",
            f"\t\t<loc>{escape(kml_url)}</loc>",
            f"\t\t<lastmod>{escape(business.lastmod)}</lastmod>",
            "\t</url>",
        ]
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n"
        "</urlset>\n"
        f"{RANK_MATH_FOOTER}\n"
    )


def write_local_seo_files() -> LocalBusiness:
    business = extract_local_business()
    (ROOT / "locations.kml").write_text(render_locations_kml(business), encoding="utf-8")
    (ROOT / "local-sitemap.xml").write_text(render_local_sitemap(business), encoding="utf-8")
    return business


def render_url_block(entry: SitemapEntry) -> str:
    lines = [
        "\t<url>",
        f"\t\t<loc>{escape(entry.loc)}</loc>",
        f"\t\t<lastmod>{escape(entry.lastmod)}</lastmod>",
    ]
    for image in entry.images:
        lines.extend(
            [
                "\t\t<image:image>",
                f"\t\t\t<image:loc>{escape(image)}</image:loc>",
                "\t\t</image:image>",
            ]
        )
    lines.append("\t</url>")
    return "\n".join(lines)


def render_urlset(entries: list[SitemapEntry]) -> str:
    body = "\n".join(render_url_block(entry) for entry in entries)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"{URLSET_OPEN}\n"
        f"{body}\n"
        "</urlset>\n"
        f"{RANK_MATH_FOOTER}\n"
    )


def render_index(files: list[tuple[str, str]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        INDEX_OPEN,
    ]
    for filename, lastmod in files:
        lines.extend(
            [
                "\t<sitemap>",
                f"\t\t<loc>{escape(f'{SITE}/{filename}')}</loc>",
                f"\t\t<lastmod>{escape(lastmod)}</lastmod>",
                "\t</sitemap>",
            ]
        )
    lines.extend(["</sitemapindex>", RANK_MATH_FOOTER, ""])
    return "\n".join(lines)


def latest_lastmod(entries: list[SitemapEntry]) -> str:
    return max(entry.lastmod for entry in entries)


def write_sitemaps() -> dict[str, int]:
    grouped = load_entries()
    index_files: list[tuple[str, str]] = []
    counts: dict[str, int] = {}

    written_files: set[str] = set()
    for base in ("post", "page", "regioes-atendidas", "servico", "category"):
        chunks = chunk_entries(grouped[base], base)
        counts[base] = len(grouped[base])
        for filename, entries in chunks:
            content = render_urlset(entries)
            (ROOT / filename).write_text(content, encoding="utf-8")
            index_files.append((filename, latest_lastmod(entries)))
            written_files.add(filename)

    business = write_local_seo_files()
    index_files.append(("local-sitemap.xml", business.lastmod))
    written_files.add("local-sitemap.xml")

    for stale in ROOT.glob("*-sitemap*.xml"):
        if stale.name != "sitemap_index.xml" and stale.name not in written_files:
            stale.unlink()

    index_files.sort(
        key=lambda item: (
            {
                "post-sitemap.xml": 0,
                "page-sitemap.xml": 1,
                "regioes-atendidas-sitemap.xml": 2,
                "local-sitemap.xml": 3,
                "servico-sitemap.xml": 4,
                "category-sitemap.xml": 99,
            }.get(item[0], 50),
            item[0],
        )
    )

    (ROOT / "sitemap_index.xml").write_text(render_index(index_files), encoding="utf-8")

    robots = (
        "User-agent: *\n"
        "Disallow:\n"
        "\n"
        f"Sitemap: {SITE}/sitemap_index.xml\n"
    )
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8")
    return counts


def main() -> None:
    counts = write_sitemaps()
    total = sum(counts.values())
    print("Sitemaps gerados (formato Rank Math SEO):")
    for name, count in counts.items():
        if count:
            print(f"  {name}: {count} URLs")
    print("  local-sitemap.xml -> locations.kml (Local SEO)")
    print("  sitemap_index.xml")
    print("  robots.txt")
    print(f"  Total: {total} URLs")


if __name__ == "__main__":
    main()
