# -*- coding: utf-8 -*-
"""Conteudo editorial das paginas municipais do silo Sul Fluminense.

Cada cidade segue o esqueleto da pagina de Volta Redonda (template):
lead (2 paragrafos) + secao "atendimento local" + 7 secoes numeradas + FAQ.
"""

HUB = ["reboque-sul-fluminense", "Reboque no Sul Fluminense"]

CITIES = []

CITIES.append({
    "slug": "reboque-em-barra-mansa",
    "city": "Barra Mansa",
    "title": "Reboque em Barra Mansa 24h | Guincho na Dutra e na BR-393",
    "desc": "Pane na Via Dutra, na Rodovia do Aço (BR-393) ou na subida da RJ-155? O serviço de reboque em Barra Mansa atende 24 horas a segunda maior cidade do Sul Fluminense, com guincho plataforma para carros, SUVs, motos e utilitários no Centro, Ano Bom, Estamparia, Saudade e nos distritos de Floriano, Rialto e Nossa Senhora do Amparo.",
    "area": "Barra Mansa, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-volta-redonda", "Reboque em Volta Redonda"], ["reboque-em-porto-real", "Reboque em Porto Real"], ["reboque-em-rio-claro-rj", "Reboque em Rio Claro"]],
    "lead": [
        '<p>Seu carro parou na <b>Via Dutra (BR-116)</b>, no fluxo da <b>Rodovia do Aço (BR-393)</b> ou na subida da <b>RJ-155</b> rumo a Rio Claro? O serviço de <b>reboque em Barra Mansa</b> atende a segunda maior cidade do <b>Sul Fluminense</b>, um município cortado pelo Rio Paraíba do Sul e por três eixos rodoviários de peso, onde o tráfego de caminhões da cadeia siderúrgica convive com o trânsito urbano de mais de 180 mil habitantes. Superaquecimento, pane elétrica, pneu estourado e colisão de baixa velocidade estão entre os chamados mais frequentes. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Ficar parado no <b>Centro</b>, no <b>Ano Bom</b>, na <b>Estamparia</b>, na <b>Saudade</b>, na <b>Colônia Santo Antônio</b> ou em um dos distritos — <b>Floriano</b>, <b>Rialto</b>, <b>Nossa Senhora do Amparo</b>, <b>Antônio Rocha</b> e <b>Santa Rita de Cássia</b> — pede um atendimento que conheça as pontes sobre o Paraíba e os acessos aos trevos da Dutra. Nossa equipe de <b>guinchos em Barra Mansa</b> trabalha com plataforma hidráulica, transportando carro, SUV, van ou moto com segurança até a oficina, a concessionária ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Barra Mansa: atendimento local",
        "p": [
            '<p>Barra Mansa é um entroncamento: a Via Dutra passa pelo município e concentra as ocorrências de estrada, a BR-393 (Rodovia Lúcio Meira) segue de Volta Redonda em direção a Três Rios e à ligação com a BR-040, e a RJ-155 — no trecho que corresponde à BR-494 — sai da cidade rumo a Rio Claro e Angra dos Reis. Some a isso a malha urbana densa entre o Centro e o Ano Bom, as pontes sobre o Rio Paraíba do Sul e o movimento das indústrias metalúrgicas e fornecedoras da CSN, e o resultado é uma demanda constante por guincho, em qualquer horário.</p>',
            '<p>Como atuamos dentro da região do Médio Paraíba, não é preciso esperar um reboque sair da capital. Confirmado o ponto exato do veículo, o tempo de chegada costuma ficar entre 15 e 30 minutos, variando com o trânsito e com a distância até o distrito. Para reboque após acidente, bateria descarregada, pneu furado ou falha mecânica, ligue (21) 95954-3043 — atendimento 24 horas.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Barra Mansa?",
         "p": 'O <b>reboque</b> é um atendimento de emergência voltado ao resgate e ao transporte de veículos que não podem circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> para automóveis de passeio, picapes, utilitários e motos.',
             '<b>Resgate em rodovia</b> na Via Dutra (BR-116), na BR-393 e no trecho da RJ-155/BR-494.',
             '<b>Apoio à frota industrial</b> das metalúrgicas e das transportadoras que abastecem a região.',
             '<b>Plataforma hidráulica</b> que preserva suspensão, câmbio e lataria durante todo o trajeto.',
         ],
         "after": '<p>O guincho garante que o seu patrimônio chegue à oficina de confiança, à concessionária ou de volta à cidade de origem com transparência e segurança.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento é direto, para tirar você do aperto o quanto antes:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa a localização exata (ex.: quilômetro da Dutra, bairro do Ano Bom ou distrito de Floriano).',
             '<b>Triagem:</b> identificamos o modelo do veículo, o tipo de pane e se há risco no local.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima de Barra Mansa.',
             '<b>Remoção:</b> o profissional faz o carregamento seguro na plataforma, com calços e cintas.',
             '<b>Destino:</b> o veículo segue até a oficina, a residência ou o pátio combinado.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Barra Mansa?",
         "p": 'Improvisar a remoção do veículo com corda ou cabo na Dutra, na Rodovia do Aço ou nas rampas da RJ-155 é perigoso e costuma sair mais caro do que o próprio serviço, por causa dos danos à transmissão e ao câmbio.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> tira você e os passageiros da exposição ao tráfego pesado de carretas.',
             '<b>Cuidado técnico:</b> equipamento adequado para carros com rodas travadas, tração integral ou câmbio automático.',
             '<b>Logística facilitada:</b> levamos o veículo para o Rio de Janeiro (cerca de 135 km pela Dutra), para São Paulo ou para qualquer cidade do Vale do Paraíba.',
             '<b>Assistência completa:</b> carga de bateria e troca de pneu no local, quando o problema permite.',
         ]},
        {"h2": "4. Quanto custa o reboque em Barra Mansa?",
         "p": 'O valor do reboque em Barra Mansa costuma variar entre <b>180 e 450 reais</b> dentro do perímetro urbano. O preço final depende de:',
         "type": "ul",
         "items": [
             'A distância entre o ponto de resgate e o destino final, sobretudo para os distritos mais afastados.',
             'O porte do veículo (moto, carro de passeio, caminhonete ou utilitário pesado).',
             'O horário do chamado (madrugada, domingo ou feriado).',
             'A complexidade do resgate (veículo em ribanceira, garagem, área alagada ou com rodas travadas).',
         ]},
        {"h2": "5. Guincho na RJ-155: a estrada de Barra Mansa para Angra dos Reis",
         "p": 'A RJ-155 nasce em Barra Mansa e é o principal elo terrestre entre o Sul Fluminense e a Costa Verde: são cerca de 90 quilômetros até a BR-101, em Angra dos Reis, com trecho de serra, curvas fechadas e túneis na altura da Serra do Capivari. É uma rota de fim de semana e de caminhão, e um lugar ruim para ficar parado.',
         "type": "ul",
         "items": [
             'Atendimento no trecho urbano e nos distritos ao longo da RJ-155, incluindo o limite com <b>Rio Claro</b> e Getulândia.',
             'Plataforma e equipamento para remoção em rampa, acostamento estreito e curva sem visibilidade.',
             'Sinalização adequada no local até a chegada do guincho, reduzindo o risco de colisão traseira.',
             'Transporte do veículo tanto para a região do Médio Paraíba quanto para o litoral, conforme o destino escolhido.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Barra Mansa reúne diferenciais que fazem diferença no tempo de resposta:',
         "type": "ul",
         "items": [
             '<b>Domínio dos acessos:</b> trevos da Dutra, pontes sobre o Paraíba do Sul e ligação com a BR-393.',
             '<b>Cobertura dos distritos:</b> Floriano, Rialto, Nossa Senhora do Amparo, Antônio Rocha e Santa Rita de Cássia.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, incluindo SUVs e picapes.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, com contato direto com o motorista do guincho.',
         ]},
        {"h2": "7. Onde atendemos em Barra Mansa?",
         "p": 'Nossa frota cobre os pontos estratégicos do município e do entorno:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> Via Dutra (BR-116), BR-393 (Rodovia do Aço), RJ-155/BR-494 e as avenidas do Centro e do Ano Bom.',
             '<b>Bairros e distritos:</b> Centro, Ano Bom, Estamparia, Saudade, Colônia Santo Antônio, Vila Maria, Boa Vista, Santa Rosa, Vila Nova, além de Floriano, Rialto, Nossa Senhora do Amparo, Antônio Rocha e Santa Rita de Cássia.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-volta-redonda/" title="Reboque em Volta Redonda">Volta Redonda</a>, <a href="../reboque-em-quatis/" title="Reboque em Quatis">Quatis</a>, <a href="../reboque-em-porto-real/" title="Reboque em Porto Real">Porto Real</a>, <a href="../reboque-em-pinheiral/" title="Reboque em Pinheiral">Pinheiral</a> e <a href="../reboque-em-rio-claro-rj/" title="Reboque em Rio Claro">Rio Claro</a>.',
         ]},
    ],
    "faq_visible": [
        ["Quanto tempo demora para o guincho chegar em Barra Mansa?", 'O tempo médio varia conforme o bairro e o trânsito nas rodovias; chamados em pista de rolamento e situações de risco têm prioridade.'],
        ["Vocês atendem na Via Dutra e na Rodovia do Aço de madrugada?", 'Sim. O atendimento é 24 horas, todos os dias, tanto no perímetro urbano quanto nos trechos de rodovia que cortam o município.'],
        ["O reboque sobe a RJ-155 em direção a Rio Claro e Angra?", 'Sim. Atendemos o trecho de serra da RJ-155, com equipamento apropriado para curvas fechadas e acostamento estreito.'],
        ["Vocês levam o carro para o Rio de Janeiro ou São Paulo?", 'Levamos. A Via Dutra liga Barra Mansa às duas capitais e fazemos transporte de longa distância com plataforma. Veja também o nosso <a href="../../" target="_blank" rel="noopener">reboque no Rio de Janeiro</a>.'],
        ["Quais as formas de pagamento aceitas?", 'Aceitamos Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Barra Mansa?", "É o atendimento de emergência para resgate e transporte de veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, com plataforma hidráulica para carros, SUVs, picapes e motos."],
        ["2. Como funciona o reboque?", "Você informa a localização exata (quilômetro da Dutra, bairro ou distrito), fazemos a triagem do veículo e da pane, acionamos a unidade mais próxima, carregamos na plataforma e levamos até o destino combinado."],
        ["3. Por que contratar um reboque profissional em Barra Mansa?", "Porque improvisar a remoção com corda na Dutra, na BR-393 ou nas rampas da RJ-155 expõe o motorista ao tráfego de carretas e pode danificar câmbio e transmissão, saindo mais caro que o próprio serviço."],
        ["4. Quanto custa o reboque em Barra Mansa?", "Em geral entre 180 e 450 reais no perímetro urbano, conforme a distância, o porte do veículo, o horário do chamado e a complexidade do resgate."],
        ["5. O guincho atende a RJ-155 rumo a Rio Claro e Angra dos Reis?", "Sim. A RJ-155 sai de Barra Mansa e liga a Dutra à BR-101, em Angra, com trecho de serra e túneis; atendemos esse percurso com equipamento próprio para rampa e curva fechada."],
        ["6. O reboque atende 24 horas em Barra Mansa?", "Sim, atendemos 24 horas por dia, 7 dias por semana, inclusive feriados, em todos os bairros, nos cinco distritos e nas rodovias que cortam o município."],
        ["7. Onde atendemos em Barra Mansa?", "Cobrimos a Via Dutra, a BR-393, a RJ-155/BR-494 e bairros como Centro, Ano Bom, Estamparia, Saudade, Colônia Santo Antônio, Boa Vista e Santa Rosa, além dos distritos de Floriano, Rialto, Nossa Senhora do Amparo, Antônio Rocha e Santa Rita de Cássia."],
        ["8. Vocês levam o carro para o Rio de Janeiro ou São Paulo?", "Sim. A Via Dutra liga Barra Mansa ao Rio (cerca de 135 km) e a São Paulo; fazemos transporte de longa distância com pagamento via Pix, débito ou crédito."],
    ],
})

CITIES.append({
    "slug": "reboque-em-barra-do-pirai",
    "city": "Barra do Piraí",
    "title": "Reboque em Barra do Piraí 24h | Guincho na BR-393",
    "desc": "Pane na BR-393 (Rodovia Lúcio Meira), na RJ-137 ou na estrada de Ipiabas? O serviço de reboque em Barra do Piraí atende 24 horas o antigo entroncamento ferroviário do Vale do Café, com guincho plataforma para carros, SUVs, motos e utilitários no Centro e nos distritos de Ipiabas, Vargem Alegre, Dorândia, Califórnia da Barra e São José do Turvo.",
    "area": "Barra do Piraí, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-valenca", "Reboque em Valença"], ["reboque-em-pirai", "Reboque em Piraí"], ["reboque-em-pinheiral", "Reboque em Pinheiral"]],
    "lead": [
        '<p>Seu veículo parou na <b>BR-393 (Rodovia Lúcio Meira)</b>, na <b>RJ-137</b> rumo a Conservatória ou na descida para o <b>Centro</b>? O serviço de <b>reboque em Barra do Piraí</b> atende uma das cidades mais estratégicas do <b>Sul Fluminense</b>: nascida do maior entroncamento ferroviário do país no século XIX, ela ainda funciona como cruzamento de estradas entre o Médio Paraíba, o Vale do Café e a Via Dutra. Ladeiras, curvas e trechos de pista simples tornam pane elétrica, superaquecimento e pneu furado ocorrências rotineiras. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Ficar imobilizado no <b>Centro</b>, na margem do <b>Rio Paraíba do Sul</b> ou em um dos distritos — <b>Ipiabas</b>, <b>Vargem Alegre</b>, <b>Dorândia</b>, <b>Califórnia da Barra</b> e <b>São José do Turvo</b> — exige um atendimento que conheça as estradas vicinais da região. Nossa equipe de <b>guinchos em Barra do Piraí</b> trabalha com plataforma hidráulica e leva carro, SUV, van ou moto com segurança até a oficina, a concessionária ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Barra do Piraí: atendimento local",
        "p": [
            '<p>Barra do Piraí é servida por três eixos: a BR-393, antiga Rio–Bahia, que corta o município e segue para Volta Redonda de um lado e Três Rios do outro; a RJ-145, que faz a ligação com a Rodovia Presidente Dutra; e a RJ-137, que sobe rumo a Conservatória e à divisa com Minas Gerais. São estradas de pista simples, com relevo ondulado e trechos sem acostamento, onde uma pane no fim da tarde vira risco real. Na área urbana, as ruas em ladeira e o entorno da antiga estação ferroviária concentram os chamados de bateria e embreagem.</p>',
            '<p>Por atuarmos dentro da região, o guincho não precisa vir da capital. Assim que o local é confirmado, o tempo de chegada gira em torno de 15 a 30 minutos na sede e um pouco mais nos distritos rurais. Para reboque após acidente, pane seca, bateria descarregada ou pneu furado, ligue (21) 95954-3043, 24 horas por dia.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Barra do Piraí?",
         "p": 'O <b>reboque</b> é o atendimento de emergência que resgata e transporta veículos impedidos de circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de automóveis, picapes, utilitários e motocicletas.',
             '<b>Resgate em rodovia</b> na BR-393, na RJ-145 e na RJ-137, inclusive em pista simples.',
             '<b>Atendimento rural</b> nas estradas vicinais que ligam a sede a Ipiabas, Dorândia e São José do Turvo.',
             '<b>Plataforma hidráulica</b> que protege suspensão, câmbio e lataria no transporte.',
         ],
         "after": '<p>O guincho garante que o veículo chegue à oficina de confiança, à concessionária ou de volta à cidade de origem com segurança e preço combinado.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O processo é simples e pensado para reduzir o tempo em que você fica parado na estrada:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa a localização (ex.: quilômetro da BR-393 ou entrada de Ipiabas).',
             '<b>Triagem:</b> identificamos o modelo do veículo, a natureza da pane e as condições do local.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima de Barra do Piraí.',
             '<b>Remoção:</b> o profissional realiza o carregamento na plataforma, com sinalização adequada.',
             '<b>Destino:</b> o veículo é entregue na oficina, na residência ou no ponto combinado.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Barra do Piraí?",
         "p": 'Puxar o carro com corda em estrada de pista simples, à noite e em relevo ondulado, é uma combinação ruim: além do risco de colisão, o arrasto danifica câmbio, embreagem e sistema de freios.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> retira o motorista e os passageiros da faixa de rolamento.',
             '<b>Cuidado técnico:</b> equipamento certo para veículos com rodas travadas ou câmbio automático.',
             '<b>Logística facilitada:</b> transportamos para o Rio de Janeiro, para Volta Redonda ou para qualquer cidade do Vale do Café.',
             '<b>Assistência completa:</b> carga de bateria, troca de pneu e apoio em pane seca no próprio local.',
         ]},
        {"h2": "4. Quanto custa o reboque em Barra do Piraí?",
         "p": 'O valor do reboque em Barra do Piraí costuma ficar entre <b>180 e 450 reais</b> no perímetro urbano. O preço final é definido por:',
         "type": "ul",
         "items": [
             'A distância entre o ponto de resgate e o destino, especialmente quando o chamado é em distrito rural.',
             'O porte do veículo (moto, carro de passeio, caminhonete ou utilitário).',
             'O horário da solicitação (noite, madrugada, domingo ou feriado).',
             'A dificuldade do resgate (estrada de terra, ribanceira, área sem acostamento).',
         ]},
        {"h2": "5. Reboque nos distritos e nas estradas do Vale do Café",
         "p": 'Boa parte do território de Barra do Piraí é rural. Ipiabas, Califórnia da Barra, Dorândia, Vargem Alegre e São José do Turvo ficam a dezenas de quilômetros da sede, em estradas estreitas que recebem movimento turístico nos fins de semana — justamente quando o socorro comum demora mais.',
         "type": "ul",
         "items": [
             'Atendimento em <b>Ipiabas</b>, a cerca de 17 km do Centro, e nas pousadas e fazendas históricas do entorno.',
             'Resgate em estrada de terra e piso irregular, com plataforma e guincho de arrasto quando necessário.',
             'Apoio a turistas que não conhecem as oficinas da região e precisam levar o carro para casa.',
             'Cobertura também na ligação com <a href="../reboque-em-valenca/" title="Reboque em Valença">Valença</a> e com o distrito de Conservatória, pela RJ-137.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Barra do Piraí traz diferenciais práticos para quem ficou na mão:',
         "type": "ul",
         "items": [
             '<b>Domínio das rotas:</b> BR-393, RJ-145, RJ-137 e os acessos à Via Dutra por Piraí.',
             '<b>Experiência em relevo:</b> motoristas acostumados a ladeira, curva fechada e estrada sem acostamento.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor acertado antes do serviço, sem cobrança surpresa na entrega.',
         ]},
        {"h2": "7. Onde atendemos em Barra do Piraí?",
         "p": 'Nossa frota cobre a sede, os distritos e as ligações regionais:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> BR-393 (Rodovia Lúcio Meira), RJ-145, RJ-137 e as estradas vicinais do Vale do Café.',
             '<b>Sede e distritos:</b> Centro e região central, Ipiabas, Vargem Alegre, Dorândia, Califórnia da Barra e São José do Turvo.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-pirai/" title="Reboque em Piraí">Piraí</a>, <a href="../reboque-em-pinheiral/" title="Reboque em Pinheiral">Pinheiral</a>, <a href="../reboque-em-valenca/" title="Reboque em Valença">Valença</a> e <a href="../reboque-em-volta-redonda/" title="Reboque em Volta Redonda">Volta Redonda</a>.',
         ]},
    ],
    "faq_visible": [
        ["Quanto tempo demora para o guincho chegar em Barra do Piraí?", 'Na sede, o tempo médio fica entre 15 e 30 minutos; nos distritos rurais o deslocamento é maior, e informamos a previsão real no momento da chamada.'],
        ["Vocês atendem Ipiabas, Dorândia e os outros distritos?", 'Sim. Atendemos todos os distritos do município, inclusive em estrada de terra e nos acessos às fazendas do Vale do Café.'],
        ["O reboque funciona de madrugada e no fim de semana?", 'Sim, o atendimento é 24 horas, todos os dias, inclusive feriados — período em que o movimento turístico aumenta na região.'],
        ["Vocês levam o carro para o Rio de Janeiro?", 'Levamos. A ligação pela RJ-145 e pela Via Dutra permite transporte de longa distância. Veja também o nosso <a href="../../" target="_blank" rel="noopener">reboque no Rio de Janeiro</a>.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Barra do Piraí?", "É o atendimento de emergência que resgata e transporta veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, com plataforma para carros, SUVs, picapes e motos."],
        ["2. Como funciona o reboque?", "Você informa o local (quilômetro da BR-393, bairro ou distrito), fazemos a triagem do veículo e da pane, acionamos a unidade mais próxima, carregamos na plataforma e entregamos no destino combinado."],
        ["3. Por que contratar um reboque profissional em Barra do Piraí?", "Porque puxar o carro com corda em pista simples e relevo ondulado expõe o motorista a colisão e danifica câmbio, embreagem e freios, saindo mais caro do que o serviço."],
        ["4. Quanto custa o reboque em Barra do Piraí?", "Em geral entre 180 e 450 reais no perímetro urbano, variando com a distância, o porte do veículo, o horário e a dificuldade do resgate, sobretudo em estrada rural."],
        ["5. Vocês atendem Ipiabas e os demais distritos?", "Sim. Atendemos Ipiabas, Vargem Alegre, Dorândia, Califórnia da Barra e São José do Turvo, incluindo estradas de terra e os acessos às fazendas do Vale do Café."],
        ["6. O reboque atende 24 horas em Barra do Piraí?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, na sede, nos distritos e nas rodovias que cortam o município."],
        ["7. Onde atendemos em Barra do Piraí?", "Cobrimos a BR-393, a RJ-145, a RJ-137 e as estradas vicinais, além do Centro e dos distritos de Ipiabas, Vargem Alegre, Dorândia, Califórnia da Barra e São José do Turvo."],
        ["8. Vocês levam o carro para o Rio de Janeiro?", "Sim. Pela RJ-145 e pela Via Dutra fazemos transporte de longa distância até a capital e outras cidades, com pagamento via Pix, débito ou crédito."],
    ],
})

CITIES.append({
    "slug": "reboque-em-pirai",
    "city": "Piraí",
    "title": "Reboque em Piraí 24h | Guincho na Serra das Araras",
    "desc": "Pane na descida da Serra das Araras ou no trecho da Via Dutra em Piraí? O serviço de reboque em Piraí atende 24 horas o trecho mais crítico da BR-116 no Sul Fluminense, com guincho plataforma para carros, SUVs, motos e utilitários no Centro e nos distritos de Arrozal, Santanésia e Cacaria.",
    "area": "Piraí, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-pinheiral", "Reboque em Pinheiral"], ["reboque-em-barra-do-pirai", "Reboque em Barra do Piraí"], ["reboque-em-volta-redonda", "Reboque em Volta Redonda"]],
    "lead": [
        '<p>Ficou parado na descida da <b>Serra das Araras</b> ou no trecho da <b>Via Dutra (BR-116)</b> que corta o município? O serviço de <b>reboque em Piraí</b> cobre um dos pontos mais delicados de toda a ligação Rio–São Paulo: entre os quilômetros 220 e 229 a rodovia se divide em pistas separadas, com declive longo, curvas e tráfego pesado de caminhões. Freio superaquecido, pane no motor e colisão traseira são ocorrências típicas desse trecho. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Além da serra, atendemos a área urbana e os distritos de <b>Arrozal</b>, <b>Santanésia</b> e <b>Cacaria</b>, bem como o entorno do <b>reservatório de Ribeirão das Lajes</b>, cercado por estradas estreitas e sem iluminação. Nossa equipe de <b>guinchos em Piraí</b> usa plataforma hidráulica e transporta carro, SUV, van ou moto com segurança até o destino escolhido.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Piraí: atendimento local",
        "p": [
            '<p>Piraí é pequena em população e enorme em importância rodoviária. A Serra das Araras, no limite com Paracambi, é o trecho onde a Dutra desce a Serra do Mar rumo à Baixada — e onde qualquer parada exige sinalização imediata, porque a visibilidade em curva é curta e a velocidade média dos caminhões é alta. O município também dá acesso à BR-393 e concentra estradas rurais que ligam a sede a Arrozal e Santanésia, com pontos sem sinal de celular.</p>',
            '<p>Trabalhamos dentro da região, o que encurta a espera: confirmado o quilômetro ou o bairro, a chegada costuma ficar entre 15 e 30 minutos, conforme a condição do tráfego na serra. Para reboque após acidente, freio superaquecido, bateria descarregada ou pneu furado, ligue (21) 95954-3043 — 24 horas.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Piraí?",
         "p": 'O <b>reboque</b> é o atendimento de emergência para resgatar e transportar veículos que não podem seguir viagem por pane, colisão, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> para carros de passeio, picapes, utilitários e motos.',
             '<b>Resgate em serra</b> na descida das Araras, com atenção especial a freio e câmbio superaquecidos.',
             '<b>Atendimento rodoviário</b> no trecho da Via Dutra e nos acessos à BR-393.',
             '<b>Plataforma hidráulica</b> que evita esforço adicional sobre a transmissão em declive.',
         ],
         "after": '<p>O guincho garante que o veículo saia do trecho de risco e chegue à oficina, à concessionária ou à cidade de destino em segurança.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento segue uma sequência simples, que prioriza tirar o veículo da pista:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa o quilômetro e o sentido da Dutra (Rio ou São Paulo) ou o bairro em Piraí.',
             '<b>Triagem:</b> avaliamos o modelo, o tipo de pane e o risco do ponto onde o veículo parou.',
             '<b>Deslocamento:</b> a central aciona a unidade mais próxima do trecho.',
             '<b>Remoção:</b> carregamento na plataforma com sinalização e, se preciso, apoio para sair do declive.',
             '<b>Destino:</b> entrega na oficina, na residência ou no pátio combinado.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Piraí?",
         "p": 'A Serra das Araras não perdoa improviso. Parar no acostamento estreito, tentar rebocar com corda ou descer o carro em ponto morto para "chegar até o posto" são decisões que terminam em acidente.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> retira você da faixa de rolamento em um trecho de alta velocidade e visibilidade curta.',
             '<b>Cuidado técnico:</b> equipamento adequado para veículo com freio ou motor superaquecido.',
             '<b>Logística facilitada:</b> transporte tanto para a Baixada e a capital quanto para o Médio Paraíba.',
             '<b>Assistência completa:</b> carga de bateria, troca de pneu e apoio em pane seca no local.',
         ]},
        {"h2": "4. Quanto custa o reboque em Piraí?",
         "p": 'O reboque em Piraí costuma variar entre <b>180 e 450 reais</b> em deslocamentos urbanos e curtos. O valor final considera:',
         "type": "ul",
         "items": [
             'A distância percorrida — chamados na serra, com retorno longo, custam mais.',
             'O porte do veículo (moto, carro, caminhonete ou utilitário pesado).',
             'O horário do chamado (madrugada, domingo ou feriado prolongado).',
             'A complexidade do resgate (declive, acostamento estreito, veículo fora da pista).',
         ]},
        {"h2": "5. Serra das Araras: o trecho mais crítico da Via Dutra",
         "p": 'Entre os km 220 e 229, a Dutra se divide em pistas independentes para vencer a Serra do Mar. É o ponto em que mais atendemos caminhoneiros e motoristas de passeio com o mesmo problema: superaquecimento de freio na descida e perda de potência na subida.',
         "type": "ul",
         "items": [
             'Atendimento nos dois sentidos, com atenção ao ponto de parada seguro mais próximo.',
             'Experiência com veículos que perderam freio ou embreagem no declive e não podem ser rebocados por arrasto.',
             'Suporte durante as obras de modernização do trecho, que alteram desvios e faixas com frequência.',
             'Cobertura também no limite com Paracambi e nos acessos à Baixada Fluminense.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Piraí soma preparo técnico e conhecimento do trecho:',
         "type": "ul",
         "items": [
             '<b>Domínio da serra:</b> motoristas que rodam diariamente entre o alto e o pé da Serra das Araras.',
             '<b>Cobertura rural:</b> Arrozal, Santanésia, Cacaria e as estradas do entorno de Ribeirão das Lajes.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, com contato direto com o motorista.',
         ]},
        {"h2": "7. Onde atendemos em Piraí?",
         "p": 'Nossa frota cobre o trecho rodoviário e toda a área do município:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> Via Dutra (BR-116), Serra das Araras, acessos à BR-393 e estradas vicinais.',
             '<b>Sede e distritos:</b> Centro, Arrozal, Santanésia, Cacaria e o entorno do reservatório de Ribeirão das Lajes.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-pinheiral/" title="Reboque em Pinheiral">Pinheiral</a>, <a href="../reboque-em-barra-do-pirai/" title="Reboque em Barra do Piraí">Barra do Piraí</a> e <a href="../reboque-em-volta-redonda/" title="Reboque em Volta Redonda">Volta Redonda</a>.',
         ]},
    ],
    "faq_visible": [
        ["Vocês atendem na descida da Serra das Araras?", 'Sim. É um dos trechos que mais atendemos, nos dois sentidos da Via Dutra, com equipamento próprio para veículo com freio ou motor superaquecido.'],
        ["Quanto tempo demora para o guincho chegar em Piraí?", 'Em geral de 15 a 30 minutos na sede e no trecho da Dutra; nas estradas rurais o tempo depende da distância até o distrito.'],
        ["O reboque atende de madrugada na rodovia?", 'Sim, o atendimento é 24 horas, todos os dias. Em pane noturna na serra, priorizamos a sinalização e a retirada rápida da faixa de rolamento.'],
        ["Meu carro perdeu o freio na descida. Pode ser rebocado?", 'Nesses casos usamos plataforma, e não arrasto: o veículo é içado e transportado apoiado, sem exigir freio ou câmbio.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Piraí?", "É o atendimento de emergência que resgata e transporta veículos parados por pane, colisão, pneu furado ou falta de combustível, com plataforma hidráulica e atenção especial ao trecho de serra da Via Dutra."],
        ["2. Como funciona o reboque?", "Você informa o quilômetro e o sentido da Dutra ou o bairro, avaliamos o veículo e o risco do local, acionamos a unidade mais próxima, carregamos na plataforma e entregamos no destino combinado."],
        ["3. Por que contratar um reboque profissional em Piraí?", "Porque a Serra das Araras tem acostamento estreito, curvas e tráfego pesado: improvisar reboque por arrasto ou descer em ponto morto costuma terminar em acidente e em dano mecânico grave."],
        ["4. Quanto custa o reboque em Piraí?", "Em geral entre 180 e 450 reais para deslocamentos curtos, variando com a distância, o porte do veículo, o horário e a complexidade do resgate na serra."],
        ["5. Vocês atendem a Serra das Araras na Via Dutra?", "Sim, nos dois sentidos, entre os quilômetros 220 e 229, inclusive durante as obras de modernização que alteram faixas e desvios."],
        ["6. O reboque atende 24 horas em Piraí?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, na sede, nos distritos e no trecho rodoviário."],
        ["7. Onde atendemos em Piraí?", "Cobrimos a Via Dutra e a Serra das Araras, os acessos à BR-393, o Centro e os distritos de Arrozal, Santanésia e Cacaria, além do entorno do reservatório de Ribeirão das Lajes."],
        ["8. Meu carro perdeu o freio no declive. Dá para rebocar?", "Sim, com plataforma: o veículo é içado e transportado apoiado, sem depender de freio ou câmbio, que é o procedimento correto nesse tipo de pane."],
    ],
})

CITIES.append({
    "slug": "reboque-em-pinheiral",
    "city": "Pinheiral",
    "title": "Reboque em Pinheiral 24h | Guincho na Via Dutra",
    "desc": "Pane no trecho da Via Dutra em Pinheiral ou nas ruas em ladeira do município? O serviço de reboque em Pinheiral atende 24 horas a cidade entre Volta Redonda, Piraí e Barra do Piraí, com guincho plataforma para carros, SUVs, motos e utilitários no Centro, Rolamão, Varjão, Ipê e demais bairros.",
    "area": "Pinheiral, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-volta-redonda", "Reboque em Volta Redonda"], ["reboque-em-pirai", "Reboque em Piraí"], ["reboque-em-barra-do-pirai", "Reboque em Barra do Piraí"]],
    "lead": [
        '<p>Seu veículo parou no trecho da <b>Via Dutra (BR-116)</b> que corta Pinheiral ou em uma das ruas em ladeira do <b>Centro</b>? O serviço de <b>reboque em Pinheiral</b> atende um município pequeno em área, mas atravessado por uma das rodovias mais movimentadas do país e cercado por <b>Volta Redonda</b>, <b>Piraí</b> e <b>Barra do Piraí</b>. Pane elétrica, superaquecimento e pneu furado no acostamento estão entre os chamados mais comuns. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Emancipado de Piraí em 1995, Pinheiral tem distrito único e uma malha urbana compacta, com bairros como <b>Rolamão</b>, <b>Varjão</b> e <b>Ipê</b> e ligações pelas rodovias estaduais <b>RJ-141</b> e <b>RJ-145</b>. Nossa equipe de <b>guinchos em Pinheiral</b> trabalha com plataforma hidráulica e leva carro, SUV, van ou moto com segurança até a oficina ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Pinheiral: atendimento local",
        "p": [
            '<p>A Via Dutra é a espinha dorsal do município: separa bairros, concentra o comércio de beira de estrada e responde pela maioria dos chamados de emergência. Parar ali significa acostamento curto, caminhões passando a poucos metros e pouca margem para tentar resolver o problema sozinho. Fora da rodovia, o terreno acidentado do Vale do Café deixa ruas íngremes que castigam embreagem e freio, principalmente em veículos mais antigos.</p>',
            '<p>Como operamos dentro do Médio Paraíba, o guincho chega sem precisar sair da capital. Confirmado o quilômetro ou o bairro, o tempo de chegada costuma ficar entre 15 e 30 minutos. Para reboque após acidente, bateria descarregada, pneu furado ou falha mecânica, ligue (21) 95954-3043, 24 horas por dia.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Pinheiral?",
         "p": 'O <b>reboque</b> é o atendimento de emergência que resgata e transporta veículos impedidos de circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de carros de passeio, picapes, utilitários e motocicletas.',
             '<b>Resgate no trecho da Dutra</b> que atravessa o município, nos dois sentidos.',
             '<b>Atendimento urbano</b> em ruas estreitas e em ladeira, onde o caminhão precisa manobrar com cuidado.',
             '<b>Plataforma hidráulica</b> que preserva suspensão, câmbio e lataria.',
         ],
         "after": '<p>O guincho garante que o veículo saia do ponto de risco e chegue à oficina de confiança ou de volta para casa com segurança.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento é organizado para reduzir ao máximo o tempo de exposição na rodovia:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa o quilômetro e o sentido da Dutra ou o bairro em Pinheiral.',
             '<b>Triagem:</b> identificamos o modelo do veículo e o tipo de pane.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima.',
             '<b>Remoção:</b> o profissional sinaliza o local e carrega o veículo na plataforma.',
             '<b>Destino:</b> entrega na oficina, na residência ou no ponto combinado.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Pinheiral?",
         "p": 'No acostamento da Dutra, cada minuto parado é risco. Tentar empurrar o carro ou rebocar com corda em uma rodovia com esse volume de caminhões é a pior alternativa possível.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> retira você e os passageiros da faixa de rolamento e do acostamento.',
             '<b>Cuidado técnico:</b> equipamento correto para veículos com rodas travadas ou câmbio automático.',
             '<b>Logística facilitada:</b> transporte para Volta Redonda, para o Rio de Janeiro ou para São Paulo pela própria Dutra.',
             '<b>Assistência completa:</b> carga de bateria e troca de pneu no local, quando o caso permite.',
         ]},
        {"h2": "4. Quanto custa o reboque em Pinheiral?",
         "p": 'O reboque em Pinheiral costuma variar entre <b>180 e 450 reais</b> em deslocamentos urbanos. O valor final depende de:',
         "type": "ul",
         "items": [
             'A distância entre o ponto de resgate e o destino final.',
             'O porte do veículo (moto, carro, caminhonete ou utilitário).',
             'O horário do chamado (noite, madrugada, domingo ou feriado).',
             'A dificuldade do resgate (rua em ladeira, garagem apertada, veículo fora da pista).',
         ]},
        {"h2": "5. Pane na Via Dutra em Pinheiral: o que fazer",
         "p": 'Se o carro falhar no trecho de Pinheiral, a sequência correta reduz muito o risco enquanto o guincho não chega:',
         "type": "ul",
         "items": [
             'Encoste o mais à direita possível, ligue o pisca-alerta e só depois desligue o motor.',
             'Coloque o triângulo a uma boa distância, contando passos largos no sentido contrário ao fluxo.',
             'Saia do veículo pelo lado do acostamento e espere atrás da defensa, nunca dentro do carro.',
             'Informe o quilômetro exato e o sentido (Rio ou São Paulo) ao ligar — isso encurta o tempo de chegada.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Pinheiral combina agilidade e conhecimento do trecho:',
         "type": "ul",
         "items": [
             '<b>Base regional:</b> equipes que rodam entre Volta Redonda, Piraí e Barra do Piraí todos os dias.',
             '<b>Domínio da rodovia:</b> familiaridade com os acessos, retornos e pontos de parada seguros da Dutra.',
             '<b>Suporte multimarcas:</b> veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, sem surpresa na entrega.',
         ]},
        {"h2": "7. Onde atendemos em Pinheiral?",
         "p": 'Nossa frota cobre o município inteiro e as ligações vizinhas:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> Via Dutra (BR-116), RJ-141, RJ-145 e as ruas de acesso ao Centro.',
             '<b>Bairros atendidos:</b> Centro, Rolamão, Varjão, Ipê e demais áreas residenciais do município.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-volta-redonda/" title="Reboque em Volta Redonda">Volta Redonda</a>, <a href="../reboque-em-pirai/" title="Reboque em Piraí">Piraí</a> e <a href="../reboque-em-barra-do-pirai/" title="Reboque em Barra do Piraí">Barra do Piraí</a>.',
         ]},
    ],
    "faq_visible": [
        ["Quanto tempo demora para o guincho chegar em Pinheiral?", 'O tempo médio fica entre 15 e 30 minutos, conforme o trânsito na Dutra e o ponto exato onde o veículo parou.'],
        ["Vocês atendem no acostamento da Via Dutra?", 'Sim, nos dois sentidos. Chamados em pista ou acostamento têm prioridade por causa do risco de colisão.'],
        ["O reboque funciona de madrugada?", 'Sim, o atendimento é 24 horas, todos os dias, inclusive feriados.'],
        ["Vocês levam o carro para Volta Redonda ou para o Rio?", 'Levamos. A própria Dutra liga Pinheiral às duas direções, e fazemos transporte de longa distância. Veja também o nosso <a href="../../" target="_blank" rel="noopener">reboque no Rio de Janeiro</a>.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Pinheiral?", "É o atendimento de emergência para resgatar e transportar veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, com plataforma hidráulica."],
        ["2. Como funciona o reboque?", "Você informa o quilômetro e o sentido da Dutra ou o bairro, fazemos a triagem do veículo e da pane, acionamos a unidade mais próxima, sinalizamos, carregamos na plataforma e entregamos no destino."],
        ["3. Por que contratar um reboque profissional em Pinheiral?", "Porque o acostamento da Via Dutra é estreito e o fluxo de caminhões é intenso: empurrar o carro ou rebocar com corda ali expõe o motorista a colisão e danifica o veículo."],
        ["4. Quanto custa o reboque em Pinheiral?", "Em geral entre 180 e 450 reais em deslocamentos urbanos, conforme a distância, o porte do veículo, o horário e a dificuldade do resgate."],
        ["5. O que fazer em caso de pane na Dutra em Pinheiral?", "Encoste à direita, ligue o pisca-alerta, posicione o triângulo a boa distância, saia do carro pelo lado do acostamento e aguarde atrás da defensa, informando o quilômetro e o sentido ao acionar o guincho."],
        ["6. O reboque atende 24 horas em Pinheiral?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, em todos os bairros e no trecho rodoviário."],
        ["7. Onde atendemos em Pinheiral?", "Cobrimos a Via Dutra, a RJ-141 e a RJ-145, além do Centro, Rolamão, Varjão, Ipê e demais áreas residenciais, com apoio às cidades vizinhas."],
        ["8. Vocês levam o carro para Volta Redonda ou para o Rio de Janeiro?", "Sim. A Via Dutra passa dentro do município e permite transporte de longa distância nos dois sentidos, com pagamento via Pix, débito ou crédito."],
    ],
})

CITIES.append({
    "slug": "reboque-em-porto-real",
    "city": "Porto Real",
    "title": "Reboque em Porto Real 24h | Guincho no polo automotivo",
    "desc": "Pane na Via Dutra na altura do km 296 ou no acesso ao polo automotivo? O serviço de reboque em Porto Real atende 24 horas a cidade que abriga a primeira fábrica de automóveis do estado do Rio, com guincho plataforma para carros, SUVs, motos, vans e frota de empresas.",
    "area": "Porto Real, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-resende", "Reboque em Resende"], ["reboque-em-quatis", "Reboque em Quatis"], ["reboque-em-barra-mansa", "Reboque em Barra Mansa"]],
    "lead": [
        '<p>Seu veículo parou na <b>Via Dutra (BR-116)</b>, na altura do <b>km 296</b>, ou em um dos acessos ao <b>polo automotivo</b>? O serviço de <b>reboque em Porto Real</b> atende a cidade que recebeu, em 2001, a primeira fábrica de automóveis do estado do Rio de Janeiro e que hoje concentra montadora, mais de duas centenas de fornecedores e um vaivém diário de vans, caminhões e carros de funcionários. Esse perfil industrial cria uma demanda muito específica: pane em horário de troca de turno, veículo de frota parado e carga que não pode esperar. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Ficar imobilizado no <b>Centro</b>, em <b>Bulhões</b>, <b>Freitas Soares</b>, <b>Jardim das Acácias</b>, <b>Jardim Real</b> ou <b>Nossa Senhora de Fátima</b> exige um socorro que conheça os acessos ao distrito industrial e à rodovia. Nossa equipe de <b>guinchos em Porto Real</b> trabalha com plataforma hidráulica e transporta carro, SUV, van ou moto até a oficina, a concessionária ou o pátio da empresa.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Porto Real: atendimento local",
        "p": [
            '<p>Porto Real é um município compacto, encaixado entre Resende, Quatis e Barra Mansa, com a Via Dutra passando ao lado do polo industrial. A rodovia responde pela maioria dos chamados de estrada — colisão, pneu estourado, superaquecimento — enquanto a malha urbana concentra ocorrências de bateria e embreagem. Como boa parte da população trabalha em turnos, o pico de chamados não segue o horário comercial: acontece de madrugada e no início da manhã, quando poucos serviços estão disponíveis.</p>',
            '<p>Por atuarmos dentro do Sul Fluminense, dispensamos o deslocamento desde a capital. Confirmada a localização, a chegada costuma ficar entre 15 e 30 minutos. Para reboque após acidente, pane elétrica, pneu furado ou falha mecânica, ligue (21) 95954-3043 — atendimento 24 horas, inclusive para empresas.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Porto Real?",
         "p": 'O <b>reboque</b> é o atendimento de emergência que resgata e transporta veículos impedidos de circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de automóveis, SUVs, picapes, vans e motocicletas.',
             '<b>Resgate rodoviário</b> no trecho da Via Dutra que margeia o município.',
             '<b>Atendimento a frotas</b> de empresas, prestadores e fornecedores do polo industrial.',
             '<b>Plataforma hidráulica</b> que preserva suspensão, câmbio e lataria, inclusive em veículo zero-quilômetro.',
         ],
         "after": '<p>O guincho garante que o veículo chegue à oficina, à concessionária ou ao pátio da empresa com segurança e prazo previsível.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento é direto, e funciona igual para pessoa física e para frota:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa a localização exata (quilômetro da Dutra, bairro ou portaria da empresa).',
             '<b>Triagem:</b> identificamos o modelo, o tipo de pane e se há restrição de acesso no local.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima de Porto Real.',
             '<b>Remoção:</b> carregamento na plataforma, com cintas apropriadas ao tipo de veículo.',
             '<b>Destino:</b> entrega na oficina, na residência ou no pátio indicado.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Porto Real?",
         "p": 'Rebocar um veículo por arrasto na Dutra ou dentro de área industrial, com tráfego de carretas e regras próprias de circulação, é arriscado e costuma custar mais caro em manutenção do que o serviço.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> retira você da faixa de rolamento em trecho de velocidade alta.',
             '<b>Cuidado técnico:</b> equipamento adequado para câmbio automático, tração integral e veículo novo.',
             '<b>Logística facilitada:</b> transporte para Resende, Volta Redonda, Rio de Janeiro ou São Paulo pela própria Dutra.',
             '<b>Assistência completa:</b> carga de bateria e troca de pneu no local, quando o problema permite.',
         ]},
        {"h2": "4. Quanto custa o reboque em Porto Real?",
         "p": 'O reboque em Porto Real costuma variar entre <b>180 e 450 reais</b> em deslocamentos urbanos. O preço final é definido por:',
         "type": "ul",
         "items": [
             'A distância entre o ponto de resgate e o destino final.',
             'O porte do veículo (moto, carro, van, caminhonete ou utilitário).',
             'O horário do chamado (turno da madrugada, domingo ou feriado).',
             'A complexidade do resgate (garagem, pátio industrial, veículo com rodas travadas).',
         ]},
        {"h2": "5. Atendimento ao polo automotivo e à frota de empresas",
         "p": 'A vocação industrial de Porto Real muda o tipo de chamado. Além do motorista comum, atendemos empresas que precisam remover veículo de pátio, prestadores com van parada e funcionários que ficam na mão em horário de turno.',
         "type": "ul",
         "items": [
             'Atendimento no entorno do polo, na altura do km 296 da Via Dutra, e nos acessos usados por fornecedores.',
             'Remoção de veículos de frota, incluindo vans e utilitários leves, com nota e prazo combinados.',
             'Disponibilidade nos horários de troca de turno, inclusive madrugada e fim de semana.',
             'Transporte para concessionárias e centros de reparo em <a href="../reboque-em-resende/" title="Reboque em Resende">Resende</a> e <a href="../reboque-em-volta-redonda/" title="Reboque em Volta Redonda">Volta Redonda</a>.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Porto Real reúne diferenciais úteis tanto para o morador quanto para a empresa:',
         "type": "ul",
         "items": [
             '<b>Domínio dos acessos:</b> trevos da Dutra, entradas do distrito industrial e ligação com Quatis e Resende.',
             '<b>Agilidade fora de horário:</b> equipes disponíveis quando a maior parte das oficinas está fechada.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, novos ou usados.',
             '<b>Orçamento claro:</b> valor acertado antes do serviço, com contato direto com o motorista.',
         ]},
        {"h2": "7. Onde atendemos em Porto Real?",
         "p": 'Nossa frota cobre o município e as ligações regionais:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> Via Dutra (BR-116) na altura do km 296, acessos ao polo industrial e vias centrais.',
             '<b>Bairros atendidos:</b> Centro, Bulhões, Freitas Soares, Jardim das Acácias, Jardim Real, Colinas e Nossa Senhora de Fátima.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-resende/" title="Reboque em Resende">Resende</a>, <a href="../reboque-em-quatis/" title="Reboque em Quatis">Quatis</a>, <a href="../reboque-em-barra-mansa/" title="Reboque em Barra Mansa">Barra Mansa</a> e <a href="../reboque-em-itatiaia/" title="Reboque em Itatiaia">Itatiaia</a>.',
         ]},
    ],
    "faq_visible": [
        ["Vocês atendem empresas e frotas em Porto Real?", 'Sim. Removemos veículos de frota, vans e utilitários leves, com valor e prazo combinados antes do serviço.'],
        ["Quanto tempo demora para o guincho chegar?", 'Em geral de 15 a 30 minutos, conforme o ponto exato e o trânsito na Via Dutra.'],
        ["O reboque atende em horário de troca de turno, de madrugada?", 'Sim. O atendimento é 24 horas, todos os dias, exatamente para cobrir os horários em que quase nada está aberto.'],
        ["Vocês levam o carro para concessionária em Resende ou Volta Redonda?", 'Levamos. O transporte entre as cidades do Sul Fluminense é rotina, e também fazemos longa distância até o Rio ou São Paulo. Veja o nosso <a href="../../" target="_blank" rel="noopener">reboque no Rio de Janeiro</a>.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Porto Real?", "É o atendimento de emergência que resgata e transporta veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, para pessoa física e para frota de empresas."],
        ["2. Como funciona o reboque?", "Você informa a localização (quilômetro da Dutra, bairro ou portaria da empresa), fazemos a triagem, acionamos a unidade mais próxima, carregamos na plataforma e entregamos no destino combinado."],
        ["3. Por que contratar um reboque profissional em Porto Real?", "Porque rebocar por arrasto na Via Dutra ou dentro de área industrial é arriscado e danifica câmbio e transmissão, sobretudo em veículos automáticos e de tração integral."],
        ["4. Quanto custa o reboque em Porto Real?", "Em geral entre 180 e 450 reais em deslocamentos urbanos, conforme a distância, o porte do veículo, o horário e a complexidade do resgate."],
        ["5. Vocês atendem o polo automotivo e frotas de empresas?", "Sim. Atendemos o entorno do polo na altura do km 296 da Via Dutra, removemos veículos de frota e vans, com prazo e valor combinados, inclusive em horário de troca de turno."],
        ["6. O reboque atende 24 horas em Porto Real?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, na área urbana e no trecho rodoviário."],
        ["7. Onde atendemos em Porto Real?", "Cobrimos a Via Dutra, os acessos ao polo industrial e bairros como Centro, Bulhões, Freitas Soares, Jardim das Acácias, Jardim Real, Colinas e Nossa Senhora de Fátima."],
        ["8. Vocês levam o carro para concessionária em outra cidade?", "Sim. Fazemos transporte para Resende, Volta Redonda e demais cidades do Sul Fluminense, além de longa distância até o Rio de Janeiro ou São Paulo."],
    ],
})

CITIES.append({
    "slug": "reboque-em-quatis",
    "city": "Quatis",
    "title": "Reboque em Quatis 24h | Guincho na Dutra e na RJ-159",
    "desc": "Pane no trecho da Via Dutra em Quatis, na RJ-159 ou na estrada para Falcão? O serviço de reboque em Quatis atende 24 horas a sede e os distritos de Ribeirão de São Joaquim e Falcão, com guincho plataforma para carros, SUVs, motos e utilitários.",
    "area": "Quatis, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-porto-real", "Reboque em Porto Real"], ["reboque-em-barra-mansa", "Reboque em Barra Mansa"], ["reboque-em-resende", "Reboque em Resende"]],
    "lead": [
        '<p>Seu carro parou no trecho da <b>Via Dutra (BR-116)</b> que passa por Quatis, na <b>RJ-159</b> ou na estrada que sobe para <b>Falcão</b>? O serviço de <b>reboque em Quatis</b> atende um município de perfil rural encaixado entre Barra Mansa, Porto Real e Resende, onde o socorro comum demora justamente porque a maior parte dos chamados acontece fora da área urbana. Pane elétrica, superaquecimento, pneu furado e atolamento em estrada de terra são as ocorrências mais frequentes. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Além da sede, atendemos os distritos de <b>Ribeirão de São Joaquim</b> e <b>Falcão</b>, ligados por estradas estreitas que seguem rumo à divisa com Minas Gerais. Nossa equipe de <b>guinchos em Quatis</b> trabalha com plataforma hidráulica e transporta carro, SUV, van ou moto com segurança até a oficina ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Quatis: atendimento local",
        "p": [
            '<p>Quatis vive entre dois mundos: o eixo da Via Dutra, ao norte, com tráfego pesado e velocidade alta, e a malha rural que liga a sede a Falcão e a Ribeirão de São Joaquim pela RJ-159 — rodovia que encontra a Dutra no distrito de Floriano, em Barra Mansa, e segue para o sul rumo a Minas Gerais. Nessas estradas, o problema não é só a pane: é a distância até o socorro, o piso irregular e a ausência de acostamento. Um pneu furado ao entardecer pode virar uma espera longa se o guincho tiver de vir de longe.</p>',
            '<p>Como já atuamos no Sul Fluminense, o deslocamento é curto. Confirmada a localização, a chegada gira em torno de 15 a 30 minutos na sede, com prazo maior nos distritos mais afastados. Para reboque após acidente, atolamento, bateria descarregada ou falha mecânica, ligue (21) 95954-3043 — 24 horas por dia.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Quatis?",
         "p": 'O <b>reboque</b> é o atendimento de emergência para resgatar e transportar veículos que não podem circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de carros de passeio, picapes, utilitários e motocicletas.',
             '<b>Resgate rural</b> em estrada de terra, piso irregular e trechos sem acostamento.',
             '<b>Atendimento rodoviário</b> no trecho da Via Dutra e ao longo da RJ-159.',
             '<b>Plataforma hidráulica</b> que protege suspensão, câmbio e lataria durante o trajeto.',
         ],
         "after": '<p>O guincho garante que o veículo saia do ponto onde parou e chegue à oficina de confiança ou de volta para casa em segurança.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento segue uma rotina simples, adaptada à realidade rural do município:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa a referência mais próxima (quilômetro da Dutra, trecho da RJ-159 ou nome da localidade).',
             '<b>Triagem:</b> identificamos o modelo do veículo, o tipo de pane e as condições do acesso.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima de Quatis.',
             '<b>Remoção:</b> o profissional avalia o piso e faz o carregamento na plataforma com segurança.',
             '<b>Destino:</b> entrega na oficina, na propriedade ou no ponto combinado.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Quatis?",
         "p": 'Em estrada rural, a tentação de resolver sozinho é grande — e é aí que o prejuízo aparece. Rebocar com corda um veículo com câmbio automático, ou tentar tirar o carro de um barranco com outro carro, danifica transmissão, suspensão e chassi.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> evita manobras improvisadas em piso solto e em trechos sem visibilidade.',
             '<b>Cuidado técnico:</b> equipamento correto para veículo atolado, com rodas travadas ou fora da pista.',
             '<b>Logística facilitada:</b> transporte para Barra Mansa, Resende, Volta Redonda ou para o Rio de Janeiro.',
             '<b>Assistência completa:</b> carga de bateria, troca de pneu e apoio em pane seca no próprio local.',
         ]},
        {"h2": "4. Quanto custa o reboque em Quatis?",
         "p": 'O reboque em Quatis costuma variar entre <b>180 e 450 reais</b> para deslocamentos curtos. O valor final depende de:',
         "type": "ul",
         "items": [
             'A distância até o destino, sobretudo quando o chamado vem de Falcão ou de Ribeirão de São Joaquim.',
             'O porte do veículo (moto, carro, caminhonete ou utilitário).',
             'O horário da solicitação (noite, madrugada, domingo ou feriado).',
             'A complexidade do resgate (atolamento, barranco, estrada de terra molhada).',
         ]},
        {"h2": "5. Reboque nas estradas rurais e nos distritos",
         "p": 'Falcão e Ribeirão de São Joaquim concentram parte importante da população e quase toda a atividade rural do município. São localidades servidas por estradas estreitas, com pontos sem sinal de celular e trechos que pioram muito depois da chuva.',
         "type": "ul",
         "items": [
             'Atendimento ao longo da RJ-159, que liga a região à Via Dutra e segue rumo à divisa com Minas Gerais.',
             'Resgate de veículo atolado ou fora da pista, com cabo e guincho de arrasto quando o acesso não permite plataforma.',
             'Apoio a produtores rurais e a utilitários de trabalho, inclusive fora do horário comercial.',
             'Cobertura na ligação com <a href="../reboque-em-barra-mansa/" title="Reboque em Barra Mansa">Barra Mansa</a>, pelo distrito de Floriano, e com <a href="../reboque-em-porto-real/" title="Reboque em Porto Real">Porto Real</a>.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Quatis resolve o principal problema de quem mora fora do centro: o tempo de espera.',
         "type": "ul",
         "items": [
             '<b>Base regional:</b> equipes que rodam diariamente entre Barra Mansa, Porto Real e Resende.',
             '<b>Experiência rural:</b> motoristas acostumados a estrada de terra, rampa e piso solto.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, sem cobrança extra na entrega.',
         ]},
        {"h2": "7. Onde atendemos em Quatis?",
         "p": 'Nossa frota cobre a sede, os distritos e as ligações regionais:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> Via Dutra (BR-116), RJ-159 e as estradas vicinais que ligam a sede aos distritos.',
             '<b>Sede e distritos:</b> Centro e bairros da sede, Ribeirão de São Joaquim e Falcão.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-porto-real/" title="Reboque em Porto Real">Porto Real</a>, <a href="../reboque-em-barra-mansa/" title="Reboque em Barra Mansa">Barra Mansa</a> e <a href="../reboque-em-resende/" title="Reboque em Resende">Resende</a>.',
         ]},
    ],
    "faq_visible": [
        ["Vocês atendem Falcão e Ribeirão de São Joaquim?", 'Sim. Atendemos os dois distritos e as estradas vicinais, inclusive em piso de terra.'],
        ["Quanto tempo demora para o guincho chegar em Quatis?", 'Na sede, em torno de 15 a 30 minutos; nos distritos o prazo é maior e informamos a previsão real na hora da chamada.'],
        ["O reboque tira carro atolado em estrada de terra?", 'Sim. Usamos cabo e guincho de arrasto quando o acesso não permite entrar com a plataforma.'],
        ["O atendimento funciona de madrugada?", 'Sim, 24 horas por dia, todos os dias, inclusive feriados.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Quatis?", "É o atendimento de emergência que resgata e transporta veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, na área urbana e nas estradas rurais."],
        ["2. Como funciona o reboque?", "Você informa a referência mais próxima (quilômetro da Dutra, trecho da RJ-159 ou localidade), fazemos a triagem, acionamos a unidade mais próxima, carregamos na plataforma e entregamos no destino."],
        ["3. Por que contratar um reboque profissional em Quatis?", "Porque improvisar em estrada rural — puxar com corda ou tirar o carro do barranco com outro veículo — danifica transmissão, suspensão e chassi, além de expor o motorista a risco."],
        ["4. Quanto custa o reboque em Quatis?", "Em geral entre 180 e 450 reais para deslocamentos curtos, variando com a distância até os distritos, o porte do veículo, o horário e a dificuldade do resgate."],
        ["5. Vocês atendem Falcão e Ribeirão de São Joaquim?", "Sim. Atendemos os dois distritos e as estradas vicinais ao longo da RJ-159, com cabo e guincho de arrasto quando o acesso não permite plataforma."],
        ["6. O reboque atende 24 horas em Quatis?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, na sede, nos distritos e no trecho da Via Dutra."],
        ["7. Onde atendemos em Quatis?", "Cobrimos a Via Dutra, a RJ-159 e as estradas vicinais, além do Centro e dos distritos de Ribeirão de São Joaquim e Falcão."],
        ["8. Vocês levam o carro para Barra Mansa, Resende ou o Rio de Janeiro?", "Sim. O transporte entre as cidades do Sul Fluminense é rotina e também fazemos longa distância até a capital, com pagamento via Pix, débito ou crédito."],
    ],
})

CITIES.append({
    "slug": "reboque-em-rio-claro-rj",
    "city": "Rio Claro",
    "title": "Reboque em Rio Claro (RJ) 24h | Guincho na RJ-155",
    "desc": "Pane na serra da RJ-155, entre a Via Dutra e Angra dos Reis? O serviço de reboque em Rio Claro (RJ) atende 24 horas a sede e os distritos de Lídice, Passa Três e Getulândia, com guincho plataforma para carros, SUVs, motos e utilitários.",
    "area": "Rio Claro, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-barra-mansa", "Reboque em Barra Mansa"], ["reboque-em-volta-redonda", "Reboque em Volta Redonda"], ["reboque-em-angra-dos-reis", "Reboque em Angra dos Reis"]],
    "lead": [
        '<p>Seu veículo parou na serra da <b>RJ-155</b>, no caminho entre a Via Dutra e a Costa Verde? O serviço de <b>reboque em Rio Claro</b>, no <b>Sul Fluminense</b>, cobre o município que abriga o trecho mais exigente dessa ligação: cerca de 90 quilômetros de rodovia entre <b>Barra Mansa</b> e <b>Angra dos Reis</b>, com serra, curvas fechadas e túneis na região do Capivari. Freio superaquecido, embreagem queimada e pneu furado em curva são chamados frequentes por aqui. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Rio Claro é um município rural, de baixa densidade e distâncias longas, com os distritos de <b>Lídice</b>, <b>Passa Três</b> e <b>Getulândia</b> espalhados ao longo da estrada e das vicinais. Nossa equipe de <b>guinchos em Rio Claro</b> usa plataforma hidráulica e transporta carro, SUV, van ou moto com segurança até a oficina, a pousada ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Rio Claro: atendimento local",
        "p": [
            '<p>A RJ-155, a Rodovia Engenheiro Francisco Saturnino Braga, é o eixo da vida no município: liga a BR-116, em Barra Mansa, à BR-101, em Angra dos Reis, e passa por Getulândia e Lídice — este último por volta do quilômetro 25. O trecho de serra, de cerca de 15 quilômetros entre Lídice e Serra d\'Água, tem declive contínuo, curvas em sequência e túneis, e a conservação do piso é uma queixa antiga dos motoristas. É lá que se concentram as panes de freio na descida e as perdas de potência na subida, sobretudo em veículo carregado no fim de semana.</p>',
            '<p>Como operamos na região, evitamos que você espere por um guincho vindo do litoral ou da capital. Confirmado o ponto — quilômetro da RJ-155 ou nome do distrito —, o tempo de chegada varia conforme a distância dentro do município. Para reboque após acidente, superaquecimento, bateria descarregada ou pneu furado, ligue (21) 95954-3043, 24 horas.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Rio Claro?",
         "p": 'O <b>reboque</b> é o atendimento de emergência que resgata e transporta veículos impedidos de circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de carros de passeio, picapes, utilitários e motocicletas.',
             '<b>Resgate em serra</b> na RJ-155, com atenção a freio, câmbio e motor superaquecidos.',
             '<b>Atendimento rural</b> nas vicinais que ligam a sede a Lídice, Passa Três e Getulândia.',
             '<b>Plataforma hidráulica</b> que dispensa esforço da transmissão em trechos de declive.',
         ],
         "after": '<p>O guincho garante que o veículo saia do trecho de risco e chegue à oficina de confiança ou de volta para casa em segurança.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento é organizado para lidar com distância e relevo:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa o quilômetro da RJ-155, o distrito ou a referência mais próxima.',
             '<b>Triagem:</b> avaliamos o modelo do veículo, o tipo de pane e o risco do ponto de parada.',
             '<b>Deslocamento:</b> a central aciona a unidade mais próxima do trecho.',
             '<b>Remoção:</b> sinalização do local e carregamento na plataforma, com atenção à inclinação.',
             '<b>Destino:</b> entrega na oficina, na residência ou no ponto combinado, na serra ou no litoral.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Rio Claro?",
         "p": 'Na serra, improviso custa caro. Descer o carro em ponto morto para "aproveitar o embalo" ou rebocar com corda em curva fechada são erros que terminam em perda total de freio e colisão.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> retira você de um trecho com acostamento curto e visibilidade limitada.',
             '<b>Cuidado técnico:</b> equipamento adequado para veículo sem freio, sem embreagem ou com motor travado.',
             '<b>Logística facilitada:</b> transporte tanto para o Médio Paraíba quanto para a Costa Verde.',
             '<b>Assistência completa:</b> carga de bateria, troca de pneu e apoio em pane seca no local.',
         ]},
        {"h2": "4. Quanto custa o reboque em Rio Claro?",
         "p": 'O reboque em Rio Claro costuma variar entre <b>180 e 450 reais</b> em deslocamentos curtos. O valor final considera:',
         "type": "ul",
         "items": [
             'A distância percorrida — chamados no meio da serra exigem trajeto mais longo.',
             'O porte do veículo (moto, carro, caminhonete ou utilitário).',
             'O horário do chamado (noite, madrugada, domingo ou feriado prolongado).',
             'A complexidade do resgate (declive, curva sem acostamento, veículo fora da pista).',
         ]},
        {"h2": "5. RJ-155: o elo entre a Dutra e a Rio–Santos",
         "p": 'A RJ-155 é a rota mais curta entre o Sul Fluminense e Angra dos Reis, e por isso recebe de tudo: carro de passeio em fim de semana, caminhão de carga e ônibus de turismo. O trecho de serra entre Lídice e Serra d\'Água é o mais crítico.',
         "type": "ul",
         "items": [
             'Atendimento nos dois sentidos, do lado da serra e do lado do vale.',
             'Experiência com pane de freio, superaquecimento e embreagem queimada em declive longo.',
             'Cuidado redobrado nos túneis e nas curvas sem acostamento, com sinalização imediata.',
             'Transporte do veículo para <a href="../reboque-em-angra-dos-reis/" title="Reboque em Angra dos Reis">Angra dos Reis</a> ou para <a href="../reboque-em-barra-mansa/" title="Reboque em Barra Mansa">Barra Mansa</a>, conforme o destino.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Rio Claro é pensado para um município de estradas longas:',
         "type": "ul",
         "items": [
             '<b>Domínio da serra:</b> motoristas que conhecem o traçado da RJ-155 e os pontos de parada seguros.',
             '<b>Cobertura dos distritos:</b> Lídice, Passa Três, Getulândia e as vicinais do entorno.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, com contato direto com o motorista.',
         ]},
        {"h2": "7. Onde atendemos em Rio Claro?",
         "p": 'Nossa frota cobre a sede, os distritos e o trecho de serra:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> RJ-155 (Rodovia Saturnino Braga), incluindo o trecho de serra e os túneis, e as estradas vicinais.',
             '<b>Sede e distritos:</b> Centro, Lídice, Passa Três e Getulândia.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-barra-mansa/" title="Reboque em Barra Mansa">Barra Mansa</a>, <a href="../reboque-em-volta-redonda/" title="Reboque em Volta Redonda">Volta Redonda</a>, <a href="../reboque-em-angra-dos-reis/" title="Reboque em Angra dos Reis">Angra dos Reis</a> e <a href="../reboque-em-mangaratiba/" title="Reboque em Mangaratiba">Mangaratiba</a>.',
         ]},
    ],
    "faq_visible": [
        ["Vocês atendem no trecho de serra da RJ-155?", 'Sim, nos dois sentidos, incluindo a região dos túneis entre Lídice e Serra d\'Água.'],
        ["Quanto tempo demora para o guincho chegar em Rio Claro?", 'Depende da distância dentro do município: a sede e Getulândia são mais rápidas; no meio da serra e em Passa Três o prazo é maior, e informamos a previsão na hora.'],
        ["Meu carro superaqueceu na subida. Posso seguir devagar?", 'Não é recomendável: seguir com o motor superaquecido pode empenar o cabeçote e transformar um reparo simples em retífica. Pare em local seguro e acione o guincho.'],
        ["Vocês levam o carro para Angra dos Reis ou para Barra Mansa?", 'Levamos nas duas direções. A RJ-155 liga a Dutra à BR-101 e fazemos o transporte conforme o destino escolhido.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Rio Claro?", "É o atendimento de emergência que resgata e transporta veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, na sede, nos distritos e no trecho de serra da RJ-155."],
        ["2. Como funciona o reboque?", "Você informa o quilômetro da RJ-155, o distrito ou a referência mais próxima; avaliamos o veículo e o risco do local, acionamos a unidade mais próxima, sinalizamos, carregamos na plataforma e entregamos no destino."],
        ["3. Por que contratar um reboque profissional em Rio Claro?", "Porque na serra o improviso é perigoso: descer em ponto morto ou rebocar com corda em curva fechada leva à perda de freio, e o acostamento curto deixa pouca margem de manobra."],
        ["4. Quanto custa o reboque em Rio Claro?", "Em geral entre 180 e 450 reais para deslocamentos curtos, variando com a distância dentro do município, o porte do veículo, o horário e a complexidade do resgate na serra."],
        ["5. Vocês atendem a RJ-155 entre a Dutra e Angra dos Reis?", "Sim. A RJ-155 liga Barra Mansa a Angra dos Reis em cerca de 90 km, com trecho de serra e túneis entre Lídice e Serra d'Água, e atendemos nos dois sentidos."],
        ["6. O reboque atende 24 horas em Rio Claro?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, na sede, em Lídice, Passa Três e Getulândia."],
        ["7. Onde atendemos em Rio Claro?", "Cobrimos a RJ-155 e as estradas vicinais, além do Centro e dos distritos de Lídice, Passa Três e Getulândia, com apoio a Barra Mansa, Volta Redonda, Angra dos Reis e Mangaratiba."],
        ["8. O carro superaqueceu na subida: dá para seguir devagar?", "Não é recomendável. Rodar com o motor superaquecido pode empenar o cabeçote; o correto é parar em local seguro e acionar o guincho para transporte em plataforma."],
    ],
})

CITIES.append({
    "slug": "reboque-em-rio-das-flores",
    "city": "Rio das Flores",
    "title": "Reboque em Rio das Flores 24h | Guincho no Vale do Café",
    "desc": "Pane na RJ-145, nas estradas do Vale do Café ou na divisa com Minas Gerais? O serviço de reboque em Rio das Flores atende 24 horas a sede e os distritos de Manuel Duarte, Taboas e Abarracamento, com guincho plataforma para carros, SUVs, motos e utilitários.",
    "area": "Rio das Flores, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-valenca", "Reboque em Valença"], ["reboque-em-barra-do-pirai", "Reboque em Barra do Piraí"], ["reboque-em-rio-claro-rj", "Reboque em Rio Claro"]],
    "lead": [
        '<p>Seu veículo parou na <b>RJ-145</b>, em uma estrada de fazenda ou no caminho para a divisa com <b>Minas Gerais</b>? O serviço de <b>reboque em Rio das Flores</b> atende um dos municípios mais rurais do <b>Sul Fluminense</b>, no coração do <b>Vale do Café</b>, onde as distâncias são longas, o relevo é ondulado e o socorro comum costuma demorar. Superaquecimento em subida, pneu furado em piso irregular e pane elétrica longe do centro estão entre os chamados mais comuns. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Atendemos a sede e os distritos de <b>Manuel Duarte</b>, <b>Taboas</b> e <b>Abarracamento</b>, além das fazendas históricas que recebem turistas nos fins de semana. Nossa equipe de <b>guinchos em Rio das Flores</b> trabalha com plataforma hidráulica e leva carro, SUV, van ou moto com segurança até a oficina ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Rio das Flores: atendimento local",
        "p": [
            '<p>Rio das Flores fica na ponta sul do Vale do Café, ligada à região pela RJ-145 — a rodovia que vem de Passa Três, em Rio Claro, passa por Taboas e Manuel Duarte e segue rumo a Valença e à divisa mineira. É uma estrada de pista simples, com trechos sem acostamento, pouca iluminação e sinal de celular irregular em alguns pontos. Some o movimento de turismo rural nos fins de semana e o resultado é uma demanda por guincho concentrada justamente quando menos oficinas estão abertas.</p>',
            '<p>Por atuarmos na região, você não depende de um reboque saindo da capital ou de Juiz de Fora. Confirmada a referência — quilômetro da RJ-145, nome do distrito ou da fazenda —, informamos a previsão real de chegada. Para reboque após acidente, superaquecimento, atolamento, bateria descarregada ou pneu furado, ligue (21) 95954-3043, 24 horas por dia.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Rio das Flores?",
         "p": 'O <b>reboque</b> é o atendimento de emergência que resgata e transporta veículos impedidos de circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de carros de passeio, picapes, utilitários e motocicletas.',
             '<b>Resgate rural</b> em estrada de terra, rampa e piso irregular, típicos do Vale do Café.',
             '<b>Atendimento a turistas</b> que não conhecem as oficinas da região e precisam levar o carro para casa.',
             '<b>Plataforma hidráulica</b> que preserva suspensão, câmbio e lataria no trajeto até a cidade.',
         ],
         "after": '<p>O guincho garante que o veículo saia da estrada e chegue à oficina de confiança, à concessionária ou de volta à cidade de origem.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento é simples e leva em conta a distância entre as localidades:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa a referência (quilômetro da RJ-145, distrito, fazenda ou pousada).',
             '<b>Triagem:</b> identificamos o modelo do veículo, a pane e as condições do acesso.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima.',
             '<b>Remoção:</b> avaliação do piso e carregamento seguro na plataforma.',
             '<b>Destino:</b> entrega na oficina, na propriedade ou na cidade combinada.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Rio das Flores?",
         "p": 'Em região rural, é comum tentar puxar o carro com uma caminhonete ou um trator. O resultado costuma ser um segundo problema: chassi torto, para-choque arrancado ou câmbio danificado.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> evita manobra improvisada em rampa, curva ou piso solto.',
             '<b>Cuidado técnico:</b> equipamento correto para veículo atolado, sem freio ou com rodas travadas.',
             '<b>Logística facilitada:</b> transporte para Valença, Barra do Piraí, Volta Redonda ou para o Rio de Janeiro.',
             '<b>Assistência completa:</b> carga de bateria, troca de pneu e apoio em pane seca no local.',
         ]},
        {"h2": "4. Quanto custa o reboque em Rio das Flores?",
         "p": 'O reboque em Rio das Flores costuma variar entre <b>180 e 450 reais</b> em deslocamentos curtos. O preço final depende de:',
         "type": "ul",
         "items": [
             'A distância até o destino, sobretudo em chamados vindos de Manuel Duarte, Taboas ou Abarracamento.',
             'O porte do veículo (moto, carro, caminhonete ou utilitário).',
             'O horário do chamado (noite, madrugada, domingo ou feriado).',
             'A dificuldade do resgate (estrada de terra, atolamento, veículo fora da pista).',
         ]},
        {"h2": "5. Reboque nas estradas do Vale do Café e na divisa com Minas",
         "p": 'O turismo histórico movimenta as fazendas do município, e boa parte dos visitantes chega de carro de passeio por estradas que não perdoam distração — cascalho solto, valetas e rampas curtas e íngremes.',
         "type": "ul",
         "items": [
             'Atendimento ao longo da RJ-145, incluindo Taboas e Manuel Duarte.',
             'Resgate de veículo atolado ou fora da pista, com cabo de aço quando a plataforma não alcança.',
             'Apoio a quem viaja de outro estado e precisa transportar o carro de volta para casa.',
             'Cobertura na ligação com <a href="../reboque-em-valenca/" title="Reboque em Valença">Valença</a> e com a divisa de Minas Gerais.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Rio das Flores existe para encurtar a espera de quem está longe do centro:',
         "type": "ul",
         "items": [
             '<b>Base regional:</b> equipes que já rodam entre Valença, Barra do Piraí e Rio Claro.',
             '<b>Experiência rural:</b> motoristas acostumados a estrada de terra, rampa e piso solto.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, sem cobrança extra na entrega.',
         ]},
        {"h2": "7. Onde atendemos em Rio das Flores?",
         "p": 'Nossa frota cobre a sede, os distritos e as estradas rurais:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> RJ-145 e as estradas vicinais que ligam a sede às fazendas e à divisa com Minas Gerais.',
             '<b>Sede e distritos:</b> Centro, Manuel Duarte, Taboas e Abarracamento.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-valenca/" title="Reboque em Valença">Valença</a>, <a href="../reboque-em-barra-do-pirai/" title="Reboque em Barra do Piraí">Barra do Piraí</a> e <a href="../reboque-em-rio-claro-rj/" title="Reboque em Rio Claro">Rio Claro</a>.',
         ]},
    ],
    "faq_visible": [
        ["Vocês atendem Manuel Duarte, Taboas e Abarracamento?", 'Sim. Atendemos a sede e os distritos, inclusive nas estradas vicinais de piso de terra.'],
        ["Quanto tempo demora para o guincho chegar?", 'Depende da distância dentro do município; informamos a previsão real no momento da chamada, com base no ponto exato onde o carro parou.'],
        ["O reboque tira carro atolado em estrada de fazenda?", 'Sim. Usamos cabo de aço e guincho de arrasto quando não é possível aproximar a plataforma.'],
        ["Estou de viagem e o carro quebrou. Vocês levam para minha cidade?", 'Levamos. Fazemos transporte de longa distância, inclusive para o Rio de Janeiro e para cidades de Minas Gerais e São Paulo.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Rio das Flores?", "É o atendimento de emergência que resgata e transporta veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, na sede, nos distritos e nas estradas rurais."],
        ["2. Como funciona o reboque?", "Você informa a referência (quilômetro da RJ-145, distrito, fazenda ou pousada), fazemos a triagem, acionamos a unidade mais próxima, avaliamos o piso e carregamos na plataforma até o destino."],
        ["3. Por que contratar um reboque profissional em Rio das Flores?", "Porque puxar o carro com caminhonete ou trator em rampa e piso solto costuma criar um segundo problema: chassi torto, para-choque arrancado ou câmbio danificado."],
        ["4. Quanto custa o reboque em Rio das Flores?", "Em geral entre 180 e 450 reais em deslocamentos curtos, variando com a distância até os distritos, o porte do veículo, o horário e a dificuldade do resgate."],
        ["5. Vocês atendem as fazendas e as estradas do Vale do Café?", "Sim. Atendemos ao longo da RJ-145, em Taboas e Manuel Duarte, e nas estradas vicinais das fazendas históricas, com cabo de aço quando a plataforma não alcança."],
        ["6. O reboque atende 24 horas em Rio das Flores?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados — período de maior movimento turístico na região."],
        ["7. Onde atendemos em Rio das Flores?", "Cobrimos a RJ-145 e as vicinais até a divisa com Minas Gerais, além do Centro e dos distritos de Manuel Duarte, Taboas e Abarracamento."],
        ["8. Estou de viagem e o carro quebrou: vocês levam para minha cidade?", "Sim. Fazemos transporte de longa distância com plataforma, inclusive para o Rio de Janeiro e para cidades de Minas Gerais e São Paulo, com pagamento via Pix, débito ou crédito."],
    ],
})

CITIES.append({
    "slug": "reboque-em-valenca",
    "city": "Valença",
    "title": "Reboque em Valença 24h | Guincho na RJ-137 e Conservatória",
    "desc": "Pane na RJ-137, na subida para Conservatória ou nas estradas do Vale do Café? O serviço de reboque em Valença atende 24 horas a sede e os distritos de Conservatória, Barão de Juparanã, Pentagna, Parapeúna e Santa Isabel do Rio Preto, com guincho plataforma para carros, SUVs, motos e utilitários.",
    "area": "Valença, Rio de Janeiro",
    "sidebar": [HUB, ["reboque-em-barra-do-pirai", "Reboque em Barra do Piraí"], ["reboque-em-rio-das-flores", "Reboque em Rio das Flores"], ["reboque-em-pirai", "Reboque em Piraí"]],
    "lead": [
        '<p>Seu veículo parou na <b>RJ-137</b>, na subida para <b>Conservatória</b> ou em uma das estradas do <b>Vale do Café</b>? O serviço de <b>reboque em Valença</b> atende a maior cidade do noroeste do <b>Sul Fluminense</b>, um polo de comércio, saúde e ensino que concentra o movimento de seis distritos e recebe turistas o ano inteiro. Relevo de serra, pista simples e trechos longos entre localidades tornam superaquecimento, embreagem queimada e pane elétrica ocorrências rotineiras. A operação local faz parte das <a href="../../regioes/">regiões atendidas</a> pela empresa.</p>',
        '<p>Ficar imobilizado no <b>Centro</b>, na saída para <b>Barão de Juparanã</b> ou em <b>Conservatória</b>, <b>Pentagna</b>, <b>Parapeúna</b> e <b>Santa Isabel do Rio Preto</b> exige um socorro que conheça as estradas da região. Nossa equipe de <b>guinchos em Valença</b> trabalha com plataforma hidráulica e transporta carro, SUV, van ou moto com segurança até a oficina, a pousada ou a cidade de destino.</p>',
    ],
    "local": {
        "h2": "Guincho e reboque em Valença: atendimento local",
        "p": [
            '<p>Valença é servida pela RJ-137, que sai da BR-393, em Barra do Piraí, sobe para Conservatória e segue até Santa Rita de Jacutinga, já em Minas Gerais, e pela RJ-145, que passa por Barão de Juparanã. São estradas de serra, com curvas em sequência, trechos de neblina e pouco acostamento — o tipo de via em que uma pane à noite exige sinalização imediata. Na área urbana, o relevo íngreme castiga embreagem e freio, e o movimento do comércio e do polo universitário concentra chamados no fim da tarde.</p>',
            '<p>Como atuamos na região, o guincho não precisa vir da capital nem de Juiz de Fora. Confirmado o ponto — rua no Centro, quilômetro da RJ-137 ou nome do distrito —, informamos a previsão real de chegada. Para reboque após acidente, superaquecimento, bateria descarregada ou pneu furado, ligue (21) 95954-3043, 24 horas por dia.</p>',
        ],
    },
    "sections": [
        {"h2": "1. O que é o serviço de reboque em Valença?",
         "p": 'O <b>reboque</b> é o atendimento de emergência que resgata e transporta veículos impedidos de circular por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível.',
         "type": "ul",
         "items": [
             '<b>Transporte seguro</b> de carros de passeio, picapes, utilitários e motocicletas.',
             '<b>Resgate em serra</b> na RJ-137 e na RJ-145, com atenção a freio e motor superaquecidos.',
             '<b>Atendimento aos distritos</b> e às estradas vicinais que ligam a sede às fazendas históricas.',
             '<b>Plataforma hidráulica</b> que preserva suspensão, câmbio e lataria em trajeto longo.',
         ],
         "after": '<p>O guincho garante que o veículo chegue à oficina de confiança, à concessionária ou de volta à cidade de origem com segurança e valor combinado.</p>'},
        {"h2": "2. Como funciona o reboque?",
         "p": 'O atendimento segue uma rotina objetiva, pensada para relevo e distância:',
         "type": "ol",
         "items": [
             '<b>Chamada:</b> você informa a localização (rua no Centro, quilômetro da RJ-137 ou distrito).',
             '<b>Triagem:</b> identificamos o modelo do veículo, o tipo de pane e o risco do local.',
             '<b>Deslocamento:</b> a central aciona a unidade de reboque mais próxima de Valença.',
             '<b>Remoção:</b> sinalização e carregamento na plataforma, com atenção à inclinação da via.',
             '<b>Destino:</b> entrega na oficina, na residência, na pousada ou na cidade combinada.',
         ]},
        {"h2": "3. Por que contratar um reboque profissional em Valença?",
         "p": 'Estrada de serra com pista simples é o pior cenário para improviso. Rebocar com corda em curva fechada, ou insistir em rodar com o motor fervendo até "chegar na cidade", transforma um reparo simples em retífica.',
         "type": "ul",
         "items": [
             '<b>Segurança pessoal:</b> retira você da pista em trecho de neblina, curva e pouco acostamento.',
             '<b>Cuidado técnico:</b> equipamento adequado para veículo sem freio, sem embreagem ou com rodas travadas.',
             '<b>Logística facilitada:</b> transporte para Barra do Piraí, Volta Redonda, Rio de Janeiro ou Minas Gerais.',
             '<b>Assistência completa:</b> carga de bateria, troca de pneu e apoio em pane seca no local.',
         ]},
        {"h2": "4. Quanto custa o reboque em Valença?",
         "p": 'O reboque em Valença costuma variar entre <b>180 e 450 reais</b> no perímetro urbano. O valor final considera:',
         "type": "ul",
         "items": [
             'A distância até o destino, sobretudo em chamados vindos de Conservatória ou Santa Isabel do Rio Preto.',
             'O porte do veículo (moto, carro, caminhonete ou utilitário).',
             'O horário da solicitação (noite, madrugada, domingo ou feriado).',
             'A complexidade do resgate (rampa, estrada de terra, veículo fora da pista).',
         ]},
        {"h2": "5. Reboque em Conservatória e nos demais distritos",
         "p": 'Conservatória, a cerca de uma hora da sede pela RJ-137, é o distrito de maior movimento turístico — conhecida pelas serenatas, recebe visitantes o ano inteiro, principalmente aos fins de semana. Barão de Juparanã, Pentagna, Parapeúna e Santa Isabel do Rio Preto completam um território extenso, servido por estradas estreitas.',
         "type": "ul",
         "items": [
             'Atendimento em Conservatória e no percurso da RJ-137, inclusive rumo à divisa com Minas Gerais.',
             'Cobertura em Barão de Juparanã, na altura da RJ-145, e nas vicinais que ligam os distritos.',
             'Apoio a turistas que ficam sem carro longe de casa e precisam de transporte de longa distância.',
             'Ligação com <a href="../reboque-em-barra-do-pirai/" title="Reboque em Barra do Piraí">Barra do Piraí</a> e com <a href="../reboque-em-rio-das-flores/" title="Reboque em Rio das Flores">Rio das Flores</a>, no restante do Vale do Café.',
         ]},
        {"h2": "6. Vantagens de quem conhece a região",
         "p": 'Nosso auto socorro em Valença combina conhecimento das estradas e disponibilidade real:',
         "type": "ul",
         "items": [
             '<b>Domínio das rotas:</b> RJ-137, RJ-145 e as vicinais que ligam a sede aos seis distritos.',
             '<b>Experiência em serra:</b> motoristas acostumados a curva fechada, neblina e piso molhado.',
             '<b>Suporte multimarcas:</b> atendimento a veículos nacionais e importados, de moto a utilitário.',
             '<b>Orçamento claro:</b> valor combinado antes do serviço, com contato direto com o motorista.',
         ]},
        {"h2": "7. Onde atendemos em Valença?",
         "p": 'Nossa frota cobre a sede, os distritos e as ligações regionais:',
         "type": "ul",
         "items": [
             '<b>Principais vias:</b> RJ-137 (ligação com a BR-393 e com Minas Gerais), RJ-145 e as estradas vicinais do Vale do Café.',
             '<b>Sede e distritos:</b> Centro e bairros da sede, Conservatória, Barão de Juparanã, Pentagna, Parapeúna e Santa Isabel do Rio Preto.',
             '<b>Cidades vizinhas:</b> também atendemos <a href="../reboque-em-barra-do-pirai/" title="Reboque em Barra do Piraí">Barra do Piraí</a>, <a href="../reboque-em-rio-das-flores/" title="Reboque em Rio das Flores">Rio das Flores</a> e <a href="../reboque-em-pirai/" title="Reboque em Piraí">Piraí</a>.',
         ]},
    ],
    "faq_visible": [
        ["Vocês atendem Conservatória e os outros distritos?", 'Sim. Atendemos os seis distritos, incluindo Conservatória, Barão de Juparanã, Pentagna, Parapeúna e Santa Isabel do Rio Preto.'],
        ["Quanto tempo demora para o guincho chegar em Valença?", 'Na sede, o tempo médio é curto; nos distritos mais afastados o deslocamento é maior, e informamos a previsão real na hora da chamada.'],
        ["O reboque sobe a serra da RJ-137 de madrugada?", 'Sim. O atendimento é 24 horas, todos os dias, com sinalização reforçada em trecho de neblina e curva fechada.'],
        ["Vocês levam o carro para o Rio de Janeiro ou para Minas?", 'Levamos. Fazemos transporte de longa distância pela RJ-137 e pela BR-393. Veja também o nosso <a href="../../" target="_blank" rel="noopener">reboque no Rio de Janeiro</a>.'],
        ["Quais as formas de pagamento aceitas?", 'Pix, cartão de débito e cartão de crédito, direto com o motorista do reboque.'],
    ],
    "faq_schema": [
        ["1. O que é o serviço de reboque em Valença?", "É o atendimento de emergência que resgata e transporta veículos parados por falha mecânica, colisão, pane elétrica, pneu furado ou falta de combustível, na sede, nos seis distritos e nas estradas de serra."],
        ["2. Como funciona o reboque?", "Você informa a localização (rua no Centro, quilômetro da RJ-137 ou distrito), fazemos a triagem do veículo e da pane, acionamos a unidade mais próxima, sinalizamos e transportamos na plataforma até o destino."],
        ["3. Por que contratar um reboque profissional em Valença?", "Porque em estrada de serra com pista simples o improviso é perigoso: rebocar com corda em curva fechada ou rodar com o motor fervendo transforma um reparo simples em retífica."],
        ["4. Quanto custa o reboque em Valença?", "Em geral entre 180 e 450 reais no perímetro urbano, conforme a distância até os distritos, o porte do veículo, o horário e a complexidade do resgate."],
        ["5. Vocês atendem Conservatória e Barão de Juparanã?", "Sim. Atendemos Conservatória pela RJ-137, Barão de Juparanã na altura da RJ-145 e os demais distritos pelas estradas vicinais, inclusive rumo à divisa com Minas Gerais."],
        ["6. O reboque atende 24 horas em Valença?", "Sim, 24 horas por dia, 7 dias por semana, inclusive feriados, na sede, nos distritos e nas rodovias estaduais da região."],
        ["7. Onde atendemos em Valença?", "Cobrimos a RJ-137, a RJ-145 e as vicinais do Vale do Café, além do Centro e dos distritos de Conservatória, Barão de Juparanã, Pentagna, Parapeúna e Santa Isabel do Rio Preto."],
        ["8. Vocês levam o carro para o Rio de Janeiro ou para Minas Gerais?", "Sim. Fazemos transporte de longa distância pela RJ-137 e pela BR-393, com plataforma e pagamento via Pix, débito ou crédito."],
    ],
})
